### ISSUE TITLE
pip3 install dtreeviz fails with error: [Errno 2] No such file or directory: 'cmake': 'cmake'

### ISSUE THREAD

**Issue by darshanputtaswamy** [parrt/dtreeviz#100]
creating build/temp.linux-x86_64-3.6/xgboost/plugin/updater_gpu
    copying xgboost/plugin/updater_gpu/README.md -> build/temp.linux-x86_64-3.6/xgboost/plugin/updater_gpu
    copying xgboost/CMakeLists.txt -> build/temp.linux-x86_64-3.6/xgboost
    copying xgboost/LICENSE -> build/temp.linux-x86_64-3.6/xgboost
    INFO:XGBoost build_ext:Building from source. /tmp/pip-build-2epm5102/lib/libxgboost.so
    INFO:XGBoost build_ext:Run CMake command: ['cmake', 'xgboost', '-GUnix Makefiles', '-DUSE_OPENMP=1', '-DUSE_CUDA=0', '-DUSE_NCCL=0', '-DBUILD_WITH_SHARED_NCCL=0', '-DHIDE_CXX_SYMBOLS=1', '-DUSE_HDFS=0', '-DUSE_AZURE=0', '-DUSE_S3=0', '-DPLUGIN_LZ4=0', '-DPLUGIN_DENSE_PARSER=0']
    error: [Errno 2] No such file or directory: 'cmake': 'cmake'

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2epm5102/xgboost/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gz2lw3e8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2epm5102/xgboost/

**Comment by Ashafix** [comment]
Looks like xgboost cannot be installed because cmake is missing.
Can you try to install cmake first and then xgboost separately?
https://stackoverflow.com/a/55825557/2776376

**Comment by darshanputtaswamy** [comment]
Thanks @Ashafix , for the quick response. I was able to install dtreeviz successfully after installing the latest cmake and xgboost. 
FYI, xgboost need cmake 3.13 or higher otherwise it will fail.
