### ISSUE TITLE
[BUG REPORT] Bug when visualizing XGBoost classifier with only one booster

### ISSUE THREAD

**Issue by TranSirius** [parrt/dtreeviz#101]
Hi,

Thanks for your tools! It's really useful to demonstrate our trained decision trees.

How to fix w.r.t. the bug:

In class `ShadowXGBDTree`:
fix the following function
```python
def get_node_samples(self):
        """
        Return dictionary mapping node id to list of sample indexes considered by
        the feature/split decision.
        """
        # Doc say: "Return a node indicator matrix where non zero elements
        #           indicates that the samples goes through the nodes."

        if self.node_to_samples is not None:
            return self.node_to_samples

        prediction_leaves = self.booster.predict(xgb.DMatrix(self.x_data, feature_names=self.feature_names),
                                                 pred_leaf=True)
###### Fix Here!!!  ###
        if len(prediction_leaves.shape) == 1:
            prediction_leaves = prediction_leaves[:]
        else:
            prediction_leaves = prediction_leaves[:, self.tree_index]
##################
        node_to_samples = defaultdict(list)
        for sample_i, prediction_leaf in enumerate(prediction_leaves):
            prediction_path = self._get_leaf_prediction_path(prediction_leaf)
            for node_id in prediction_path:
                node_to_samples[node_id].append(sample_i)

        self.node_to_samples = node_to_samples
        return node_to_samples
```

Best Wishes!
Zijun

**Comment by parrt** [comment]
@tlapusan can you take a look?

**Comment by tlapusan** [comment]
Hi @TranSirius, thanks for your comment, I will take a look in the next few days

**Comment by tlapusan** [comment]
hi @TranSirius, 
Just to see if I've understood correctly, you have an `IndexError: too many indices for array` when you train a xgboost model with only one tree. When the model contains more trees, the code is working.

Is this your usecase ? a model with only one tree ?

**Comment by TranSirius** [comment]
Hi @tlapusan 

Thanks for your attention

Exactly! I got an IndexError when I try to visualize a XGBoost model  with only one tree using `dtreeviz.trees.dtreeviz(xgb_model, , d[features], d[target], features, target, class_names=['N', 'Y'], tree_index = 0)`, where `d[features]` are feature vectors, `d[target]` are target vectors, `features` and `target` are their name.

That's exactly my use case: A xgboost model (boosting model) with one tree (one booster).

**Comment by tlapusan** [comment]
Hi @TranSirius,

I've just created a PR. @parrt can we make a new release with this patch ?

@TranSirius would you like to share some thoughts about dtreeviz library? namely are you using it for work, personal development, which visualizations do you find the most useful for tree interpretation ?

Thanks again for finding this bug and creating an issue !

**Comment by TranSirius** [comment]
Hi @tlapusan 

Sure, thanks for your invitation! I'd like to share my opinion with you.

I am a researcher in the fields of Natural Language Processing and Data Mining and recently I am undergoing a study, in which I would like to demonstrate that our proposed neural methods can create high quality vectors in the semantic space, which can be naturally adopted by symbolic methods, such as decision tree. However, we find difficulty to visualize the partition on decision trees in high dimensional (more than 3 dimensions) feature space. We made an investigation to find existing methods which can neatly solve our requirement, and surprisingly found dtreeviz, which neatly solves our problem. It's quite novel to decouple the high dimensional space into single dimensions and show the partition of decision tree focusing on that dimension.

Best Wishes!

**Comment by parrt** [comment]
Thanks, @tlapusan.  @TranSirius  can you upgrade? I just pushed out 1.1.1 with this fix. Please let us know if it works!

**Comment by tlapusan** [comment]
> Hi @tlapusan
> 
> Sure, thanks for your invitation! I'd like to share my opinion with you.
> 
> I am a researcher in the fields of Natural Language Processing and Data Mining and recently I am undergoing a study, in which I would like to demonstrate that our proposed neural methods can create high quality vectors in the semantic space, which can be naturally adopted by symbolic methods, such as decision tree. However, we find difficulty to visualize the partition on decision trees in high dimensional (more than 3 dimensions) feature space. We made an investigation to find existing methods which can neatly solve our requirement, and surprisingly found dtreeviz, which neatly solves our problem. It's quite novel to decouple the high dimensional space into single dimensions and show the partition of decision tree focusing on that dimension.
> 
> Best Wishes!

Sounds great, thanks for sharing this !
