### ISSUE TITLE
Replace (regression-)plot

### ISSUE THREAD

**Issue by gunthergl** [parrt/dtreeviz#102]
(How) Can I replace the node-plots from dtreeviz by a custom plot function from me?

So I opened a [stackoverflow-question](https://stackoverflow.com/questions/63968652/dtreeviz-replace-plot-regression-too-many-points) yesterday but it seems to be ill-posed (as I only got 10 views until now), so I decided to bother here directly. 

Best regards

**Comment by parrt** [comment]
unfortunately there's no way for you to pass in a custom plot. You would have to alter the software.
