### ISSUE TITLE
Better solution to solving path problem after installing graphviz for Windows.

### ISSUE THREAD

**Issue by hajimurtaza** [parrt/dtreeviz#111]
1. Install windows package from: https://graphviz.gitlab.io/_pages/Download/Download_windows.html
2. Install python `graphviz` package
3. Add `C:\Program Files (x86)\Graphviz2.38\bin` to User path
4. Add `C:\Program Files (x86)\Graphviz2.38\bin\dot.exe` to System Path

**Comment by parrt** [comment]
Thanks. cleaning up the readme.
