### ISSUE TITLE
make xgboost optional dependency

### ISSUE THREAD

**Issue by oegedijk** [parrt/dtreeviz#114]
Hi there,

Would it be possible to make xgboost an optional dependency? Reason being that the package takes up a lot of space (>350MB), and presumably:
1. Users that **want** to visualize xgboost trees already have it installed
2. Users that **don't want** to visualize xgboost trees do not need to install it.

Main reason for asking is that this dependency makes it quite a bit more complicated to deploy [explainerdashboard](http://github.com/oegedijk/explainerdashboard) dashboards to heroku.com, as there is a 500MB deployment size limit. There is a work around that I document [here](https://explainerdashboard.readthedocs.io/en/latest/deployment.html#deploying-to-heroku), but would be more convient if it would be possible to install dtreeviz without xgboost. You could add it as an optional dependency, i.e. `pip install dtreeviz[xgboost]`. 

I guess you would just have to wrap the xgboost imports in try except blocks, or only import xgboost when you try to build an xgboost shadow tree. If you want, I could have a stab at a PR to make the import optional. 

Cheers
Oege

**Comment by oegedijk** [comment]
Just noticed that there is already a PR for this: #99

**Comment by tlapusan** [comment]
Hi @oegedijk,

PR #99 wasn't functional... but one possible solution is suggested in the last comments. If you can make it work, it would be great.

**Comment by oegedijk** [comment]
done: #115
