### ISSUE TITLE
Using dtreeviz with sklearn pipelines

### ISSUE THREAD

**Issue by windisch** [parrt/dtreeviz#120]
When the following `model`

```
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeRegressor

model = make_pipeline(KNNImputer(), DecisionTreeRegressor())
```
is plugged into the function `dtreeviz.trees.dtreeviz`, this exception is raised:

```
ValueError: Tree model must be in (DecisionTreeRegressor, DecisionTreeClassifier, xgboost.core.Booster, but was Pipeline
```

Are there any plans to make sklearn's [pipelines](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html) work for `dtreeviz`?

**Comment by parrt** [comment]
Hi.  well a pipeline could have 30 different elements in it... it's up to you to pull out the specific model you'd like to visualize.

**Comment by windisch** [comment]
Thanks for your quick response! 

In my toy model above, the decision tree is at the end and cannot be pulled out of the pipeline as it needs all prior steps (in the toy example, only the imputing, but there may be more) to be executed. An example which may highlights my point is the following:

```
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import PolynomialFeatures

model = make_pipeline(KNNImputer(), PolynomialFeatures(degree=2), DecisionTreeRegressor())
```

Here, pulling out the `DecisionTreeRegressor` would change the model, as  the decision tree in `model` operates on a totally different features space than a decision tree fitted on data without the `PolynomialFeatures` preprocessor before. 

I'm happy to help implementing the pipeline support. I was just wondering whether there exist already plans to implement this.

**Comment by parrt** [comment]
```
t = DecisionTreeRegressor()
model = make_pipeline(KNNImputer(), PolynomialFeatures(degree=2), t)
```

**Comment by windisch** [comment]
If I understand you correctly, it should work with the existing implementation. I don't understand how.

Using like that
```
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import load_boston

from dtreeviz.trees import dtreeviz

t = DecisionTreeRegressor()
model = make_pipeline(KNNImputer(), PolynomialFeatures(degree=2), t)

boston = load_boston()
model.fit(boston.data, boston.target)

viz = dtreeviz(
    t,
    boston.data,
    boston.target,
    target_name='price',
    feature_names=boston.feature_names)
```
will raise an `IndexError` in `dtreeviz.models.shadow_decision_tree.py` (probably because a feature is accessed which does not exist in `boston.data` as it is generated by `PolynomialFeatures`. 

On the other hand, forwarding `model` itself to `dtreeviz` the `ValueError` from above is raised.

**Comment by parrt** [comment]
Oh sorry. you are right. If you are changing the structure of the data then you will need to pass the data coming out of the previous element of the pipeline to dtreeviz.  That is inconvenient, but you can easily just get another variable attached to the polynomial features object. I'm not sure there's much advantage to those pipelines and so I just manually process the data.  sorry I can't be more help.

**Comment by tlapusan** [comment]
@windisch I assume that sklearn Pipeline should have an API to obtained the trained dataset and the trained model. 

I've made a little research, and this link may help : https://stackoverflow.com/questions/48743032/get-intermediate-data-state-in-scikit-learn-pipeline

Here is how to get the training data, using [fit_transform](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.fit_transform) :
<img width="685" alt="Screen Shot 2021-01-11 at 9 51 11 AM" src="https://user-images.githubusercontent.com/12815158/104156834-94e29380-53f2-11eb-975c-b5be6de19bf9.png">

The trained model can be obtained from `model.named_steps`.

I'm confident you will find the solution, especially if you search for links like that from stackoverflow.

**Comment by windisch** [comment]
@tlapusan: Thanks for your reply and your research! I have a similar workaround, however, I split the pipeline into to and then calling `fit_transform` only on the first part to not re-fit the tree model onto the new data. I was wondering (and that's actually the reason why I opened this feature request) whether all of this can (or should?) be done within `dtreeviz` internally, so that the user can just plug in his pipeline (with a decision tree model at the end). If you are interested I can try to integrate my solution into `dtreeviz`. What do you think?

**Comment by tlapusan** [comment]
@windisch definitely it's an idea we should discuss. thanks for mentioning it !

How do you think the API for dtreeviz should look to support sklearn pipelines ?

Right now, dtreeviz has support for sklearn, xgboost, pyspark (plans to add for lightgbm and catboost) and vizualisations methods are expecting arguments like these :
1. raw tree model, training dataset, features, etc
2. an implementation of ShadowDecTree, which also requires to have upfront the training dataset, features...

It could be a little difficult to include sklearn pipelines, without affecting the API... but sklearn pipeline it's a valid use case for dtreeviz (I expect that many people are in this use case like you, but you were the first one to create an issue ;) )

Another idea would be have a clear idea how we can extract the training dataset, features, raw model from Pipeline (maybe without workarounds, if it's possible...). Having this variables, we can use dtreeviz as it is... AND we could write an example in one of our notebooks.

**Comment by windisch** [comment]
Hi @tlapusan: Sounds great. I haven't put to much thought into how the API should look like, but I can dig a bit deeper into how `dtreeviz` handels models and data objects to eventually come up with a implementation proposal.  Can I come back to you in case of questions?

**Comment by tlapusan** [comment]
@windisch sure, we can discuss on this topic. thanks.

please don't forget the other idea, of extracting the model, training dataset, features from Pipeline and use them in dtreeviz (as it is). For me, it sounds like a good approach :)

**Comment by windisch** [comment]
@tlapusan: [This is](https://github.com/windisch/dtreeviz/commit/a11e52c74a8354d4940e7ee28539f60e8aa07ac8) how we may can make it work. What do you think? If this goes into the right direction, I will finish this up and will open a PR the next days.

**Comment by tlapusan** [comment]
hi @windisch, I've looked over your code, I liked that you created also unit tests 👍 
My thoughts about this approach :
1. we still need to initialize ShadowSKDTree with x_data, y_data, features, but they are not training dataset used by the model, they are the raw datasets. (a clear example can be seen in your pytest module) This can create confusion to the API and also the initialization process can be a heavy one for ShadowSKDTree if we are dealing with big pipelines.
2. The ShadowSKDTree scope should be to get the model metadata through its API, not to preapare the training dataset, features, etc

Anyway, your code is valuable and other people can benefit from it :
- we can create a notebook example, so people could see how to extract the needed arguments from a sklearn pipeline.
- we can create a utility module in dtreeviz which could analyze the the pipeline and return the arguments needed by ShadowSKDTree.

@parrt, @windisch what do you think ?

**Comment by windisch** [comment]
@tlapusan: thanks for your comments. I tried to make as less changes to `ShadowSKDTree` as possible, and extracting all necessary information in its constructor and then pushing it upstream seemed canonical to me. But you are right, in case of big pipelines, applying the transformation-part of the pipeline might be very time intensive.

To 1): Yes, `x_data` and `y_data` are not necessarily the train datasets, but to apply  the model on them, we have to transform them first (as we would do in training, but without fitting the model).

To 2): I see your point!

To 3): I think you are right, there may be scenarios where the tree model is not the last step of the pipeline (but I think they are rare).

If I understand you correctly, than instead of having

```
viz = dtreeviz(
    my_pipeline,
    data_x,
    data_y,
    target_name=my_target,
    feature_names=my_feature_names)
```

and doing all the (may heavy) computations in the constructor of `ShadowSKDTree`,  you instead suggest to have something like this:

```
data_x_transfomed, my_feature_names_transfomed, tree_of_pipeline = some_helper(my_pipeline, data_x, data_y)

viz = dtreeviz(
    tree_of_pipeline,
    data_x_transfomed,
    data_y,
    target_name=my_target,
    feature_names= my_feature_names_transfomed)
```

Am I correct?  I'm fine with both ways. I can implement this helper and try to set up a notebook explaining how to use it.

**Comment by tlapusan** [comment]
Hi @windisch,
I'm also for some_helper version

**Comment by windisch** [comment]
@tlapusan: Whats the recommended place to put utitlities in `dtreeviz`?

**Comment by parrt** [comment]
@windisch i think we have a utils.py

**Comment by windisch** [comment]
This can me closed! Thanks for merging!
