### ISSUE TITLE
Readme.md - Broken link to fast.ai's Introduction to Machine Learning...

### ISSUE THREAD

**Issue by davcem** [parrt/dtreeviz#122]
The link in the Description section to "fast.ai's Introduction to Machine Learning for Coders MOOC." (last sentence) is broken.

**Comment by tlapusan** [comment]
thanks @davcem , good catch ! maybe fast.ai changed the course to another link. 

I assume the hyperlink should go to https://course18.fast.ai/ml.html.  Is it correct @parrt ?

**Comment by davcem** [comment]
You are welcome. Yes, I also thought that. 
At least from my perspective, the course description looks good.
The "outdated" link is also used at the end of the Readme in section "Useful Resources".

**Comment by parrt** [comment]
That sounds right, @tlapusan  :)
