### ISSUE TITLE
how to interpret

### ISSUE THREAD

**Issue by zahs123** [parrt/dtreeviz#125]
using the example you have given: 

![Capture](https://user-images.githubusercontent.com/23192374/107078144-d0039700-67e5-11eb-95cd-63cad7228a4b.PNG)

how should i interpret, the first branch, when you say < and > is it where the arrow is (6.94).. traversing down are we showing teh feature (x axis) vs the dependent variable (yaxis) 

just want to ensure i am interpreting it correctly.

**Comment by parrt** [comment]
Hi.  The wedge and the vertical dashed line indicates where we are splitting the RM variable at the root. Notice that the left child is now using a different variable LSTAT, but the right  is using the same RM.  Means on the right can see that the node is testing only things that were to the right of 6.94.
