### ISSUE TITLE
shadow_decision_tree.py: importing from collections raises a DeprecationWarning in Python 3.9

### ISSUE THREAD

**Issue by juliangilbey** [parrt/dtreeviz#128]
Hi there!

Running the tests gave the following warning:
```
  /usr/lib/python3/dist-packages/dtreeviz/models/shadow_decision_tree.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Sequence
```

The solution is to replace this line with:
```python
    from collections.abc import Sequence
```

**Comment by tlapusan** [comment]
thanks @juliangilbey , we will check and replace it in the next PRs

**Comment by parrt** [comment]
We'll have to do the "if version..." thing

**Comment by juliangilbey** [comment]
Or a try/except block.  But `collections.abc` was introduced in Python 3.3, back in 2012, so it's probably safe to not do an "if version..." thing!

**Comment by tlapusan** [comment]
I'm expecting also the collections.abc to return the same results as collections, but we have to test this.

**Comment by juliangilbey** [comment]
`Sequence` is defined in `_collections_abc.py`.  Then `collections/abc.py` reads:
```python
from _collections_abc import *
from _collections_abc import __all__
from _collections_abc import _CallableGenericAlias
```
while `collections/__init__.py` reads, in part:
```python
import _collections_abc
[...]
def __getattr__(name):
    # For backwards compatibility, continue to make the collections ABCs
    # through Python 3.6 available through the collections module.
    # Note, no new collections ABCs were added in Python 3.7
    if name in _collections_abc.__all__:
        obj = getattr(_collections_abc, name)
        import warnings
        warnings.warn("Using or importing the ABCs from 'collections' instead "
                      "of from 'collections.abc' is deprecated since Python 3.3, "
                      "and in 3.10 it will stop working",
                      DeprecationWarning, stacklevel=2)
        globals()[name] = obj
        return obj
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
```
Alternatively, we could just run Python to find out:
```
Python 3.9.1+ (default, Feb  5 2021, 13:46:56) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import Sequence
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
>>> Sequence
<class 'collections.abc.Sequence'>
```
So there you have it: `from collections import Sequence` makes `Sequence` be `collections.abc.Sequence`.

Best wishes, Julian

**Comment by tlapusan** [comment]
thanks @juliangilbey for making this investigation

**Comment by tlapusan** [comment]
@juliangilbey could you share a little in which use-cases are you using dtreeviz ? your answer would help us to better understand how the community is using it. thanks

**Comment by juliangilbey** [comment]
Hi @tlapusan, I've just started working with decision trees and random forests for the first time, and I'm using the Fastai book (https://github.com/fastai/fastbook) as a guide.  They introduce `dtreeviz` in chapter 9, and it's great!  So I've just made a preliminary package of it for Debian and am using it to help me understand the strange data I have.

**Comment by tirkarthi** [comment]
I have created PR https://github.com/parrt/dtreeviz/pull/130 to fix this. Since setup.py mentions that python 3.6+ is required using collections.abc directly will fix the issue.
