### ISSUE TITLE
Warning for tree index

### ISSUE THREAD

**Issue by mburaksayici** [parrt/dtreeviz#134]
Was trying for LGBM regression tree. Huge thanks for this new feature. Forgot to add tree_index parameter, and couldn't see a warning that emerges me to specify tree index. 

This gave me: 

viz = dtreeviz(model,
               train[model_features] ,
               train[target] ,
               target_name='Cons',
               feature_names=np.array(model_features))
 
This:
---> 58         tree_dump = self.booster.dump_model()["tree_info"][self.tree_index]
     59         _walk_tree(tree_dump["tree_structure"], node_index)
     60 

TypeError: list indices must be integers or slices, not NoneType_

Since tree_index not defined on function, this error happens. It should be a better a warning on specifying tree index.

**Comment by tlapusan** [comment]
thanks @mburaksayici for this suggestion. It is perfect valid, we will implement it in the next PRs.
