### ISSUE TITLE
Plot arbitrary tree

### ISSUE THREAD

**Issue by Cattes** [parrt/dtreeviz#142]
Is it possible to use the package to visualize a regression tree without using a tree object resulting of the packages `scikit-learn`, `XGBoost`, `Spark MLlib` or `LightGBM` listed in the https://github.com/parrt/dtreeviz#description ?

I am working on a package that fits a logistic regression tree and I am looking for a plotting framework to use and your package is by far the best I could find.

Since I have access to all information like split points, estimated parameters, fitted values etc. I was hoping that it's possible to create a class that contains all the necessary properties and methods needed for your plotting library to work.

**Comment by parrt** [comment]
Hmm...we'd have to build an adaptor of some kind I'm afraid.  Is this one of your own libraries or another? thanks!

**Comment by Cattes** [comment]
> Is this one of your own libraries or another?

During my master I compared multiple methods for binary classification for a seminar paper and one is an algorithm that is only available as a FORTRAN 90 executable and I am writing a package around it to make it more accessible. So it is my own python library which is currently under development.

> Hmm...we'd have to build an adaptor of some kind I'm afraid

I was hoping that I could write an adaptor class on my own for your package if it is possible.

I was assuming that you are using a subset of the implemented properties / functions of the `classifier` object passed to the `dtreeviz` function https://github.com/parrt/dtreeviz#classification-decision-tree

```python
viz = dtreeviz(classifier, 
               iris.data, 
               iris.target,
               target_name='variety',
               feature_names=iris.feature_names, 
               class_names=["setosa", "versicolor", "virginica"]  # need class_names for classifier
              )  
```

and that if I can create a custom class which also has these needed properties / methods the plotting will work.

This approach worked for me to piggyback the plotting framework of a library in `R` for the seminar paper.

**Comment by parrt** [comment]
we actually make a shadow tree to unify all models' trees.  You'd have to build an adaptor and pass the shadow tree in to our methods

**Comment by Cattes** [comment]
Thank you for the help.

I will implement a new class similar to [ShadowSKDTree](https://github.com/parrt/dtreeviz/blob/829d5bceed998d547d4ffecdabdb73c778945f8d/dtreeviz/models/sklearn_decision_trees.py) or the others described in [the readme](https://github.com/parrt/dtreeviz#visualization-methods-setup) and then I can use `dtreeviz(my_curstom_shadow_class)` to plot my tree.

**Comment by Cattes** [comment]
Hi @parrt 
the implementation of a custom ShadwTree class worked very good for numerical splits, but I have a problem implementing categorical splitting.

The tree that I am trying to plot has splits of the form of `year in [74, 80]` instead of `year < 80`.

I adjusted the `get_node_split` method to return `[[74, 80]]` for the categorical splits, which allowed the plotting to finish without an error, but the plot is distorted:
<img width="643" alt="tree_not_ploted_right" src="https://user-images.githubusercontent.com/32700350/118180571-35d76e80-b426-11eb-921b-9149763a4240.PNG">

The tree is supposed to have the following form. 

```python
 Node 1: cylinder <= 4.0000E+00
   Node 2: year = 70, 71, 72, 73, 74, 75, 76, 77, 78, 80, 81  
     Node 4: year = 70, 73, 74, 75, 80  
       Node 8: year = 70, 73, 75  
         Node 16: Probability = 0.1250E+00
       Node 8: year = 74, 80  
         Node 17: Probability = 0.2195E+00
     Node 4: year = 71, 72, 76, 77, 78, 81  
       Node 9: Probability = 0.3571E+00
   Node 2: year = 79, 82  
     Node 5: Probability = 0.6000E+00
 Node 1: cylinder > 4.0000E+00
   Node 3: year = 76, 78, 80, 81  
     Node 6: year = 80, 81  
       Node 12: Probability = 0.5455E+00
     Node 6: year = 76, 78  
       Node 13: Probability = 0.8684E+00
   Node 3: year = 70, 71, 72, 73, 74, 75, 77, 79, 82  
     Node 7: Probability = 0.9795E+00
```
(This is the original returned tree, I transform the "Node 1", "Node 2" node names to be monotonically increasing integers from 0 to n_nodes)

Is there an example for a categorical tree splitting I could follow?

**Comment by tlapusan** [comment]
hi @Cattes, looks promising ;)
you can take a look at lightGBM implementation : https://github.com/parrt/dtreeviz/blob/master/dtreeviz/models/lightgbm_decision_tree.py

There is a method is_categorical_split(). you can check how it is defined and where it is used to determine if to plot a categorical node.

**Comment by Cattes** [comment]
Hi @tlapusan 
Sorry for answering so late and for leaving a stale Issue. Life happened and I stopped tackling the problem of using the categorical splitting for now. You can close this Issue and If i continue work on my library and fix the plotting part I will update this Issue :+1:

**Comment by tlapusan** [comment]
Hi @Cattes,
thanks for answering ;)
