### ISSUE TITLE
memory error for big big trees 

### ISSUE THREAD

**Issue by benjamin-du** [parrt/dtreeviz#143]
Hi Terence,

first of all, thank you for this amazing library (and for the great blog articles you put out there). 
I'm writing here because I experience an issue with a tree that has a big depth. 
Would it be possible to somehow tell dtreeviz that we want to plot only the first part of such a tree (say, the first four splits) ? That would help avoid memory errors when the tree is too big and the structure gets out of hand.

Thank you for your time

**Comment by tlapusan** [comment]
hi @benjamin-du,

would be possible to build the tree only with depth=4 and to visualize it ? It should be the same as making from dtreeviz to visualize only the first 4 levels... i think.

**Comment by benjamin-du** [comment]
Hi, that's a good point, alas I don't have the hand on the training, I just have models stored for the last two years and cannot retrain them with arbitrary parameters without changing the company source code and saved results. 
Thank you for your answer !

**Comment by tlapusan** [comment]
In this case you have a valid request for making the visualizations adjustment from dtreeviz :)

**Comment by tlapusan** [comment]
I've added a parameter 'depth_range_to_display', which can take a range of depth levels to be displayed. Like in the picture bellow.

<img width="1014" alt="Screenshot 2021-05-27 at 10 55 31" src="https://user-images.githubusercontent.com/12815158/119787771-3b2ec180-beda-11eb-8e41-9b68167ec4b6.png">

@parrt what do you think ?

**Comment by benjamin-du** [comment]
Hi, 

great job ! Yes I still have access to the data. I'll try this feat and let you know how it goes. 

thanks a lot!

**Comment by tlapusan** [comment]
@benjamin-du this new functionality is not yet released. I will make a PR soon and if everything is ok, @parrt will make a new release
