### ISSUE TITLE
When installing dtreeviz with conda the pyspark is installed

### ISSUE THREAD

**Issue by pplonski** [parrt/dtreeviz#144]
Hi!

I was installing dtreeviz with conda:

```
conda install -c conda-forge dtreeviz
```

and I noticed that pyspark is installed - don't know why? I guess it shouldn't.

I'm on windows 10, python 3.8.5.

**Comment by parrt** [comment]
Hmm...weird. It should only install the lib unless you use an option:

```
pip install dtreeviz             # install dtreeviz for sklearn
pip install dtreeviz[xgboost]    # install XGBoost related dependency
pip install dtreeviz[pyspark]    # install pyspark related dependency
pip install dtreeviz[lightgbm]   # install LightGBM related dependency
```

**Comment by pplonski** [comment]
I just checked and on Ubuntu 20.04 it also install pyspark with dtreeviz ... very strange ...

**Comment by pplonski** [comment]
The issue is that in conda recipe all additional packages are installed - there are no versions(extensions) like in pip. Take a look at https://github.com/conda-forge/dtreeviz-feedstock/blob/master/recipe/meta.yaml

@raybellwaves is it possible to add different versions of installations in dtreeviz in conda recipe?

**Comment by raybellwaves** [comment]
I believe there is but it's not trivial. See airflow as an example https://github.com/conda-forge/airflow-feedstock/blob/master/recipe/meta.yaml

**Comment by parrt** [comment]
Hiya. I only do the pip not conda install so I'm not sure.

**Comment by pplonski** [comment]
I'm closing the issue. Right now there are two packages on conda-forge channel:
- `dreeviz` - it has required packages installed only https://anaconda.org/conda-forge/dtreeviz
- `dtreeviz-extended` - it has required and additional packages (lightgbm, xgboost, pyspark) installed https://anaconda.org/conda-forge/dtreeviz-extended

Package can be installed:
```
conda install -c conda-forge dtreeviz
```
or in extended version:
```
conda install -c conda-forge dtreeviz-extended
```

The recipe for creating packages in conda is here https://github.com/conda-forge/dtreeviz-feedstock

@raybellwaves thank you for your help!
