### ISSUE TITLE
class name font could not change

### ISSUE THREAD

**Issue by HidenariUoi** [parrt/dtreeviz#145]
I want to change the fontname below.
But, only class name font could not change.

viz = dtreeviz(
    clf,
    iris.data, 
    iris.target,
    target_name='variety',
    feature_names=iris.feature_names,
    class_names=iris.target_name ,
    fontname='IPAPGothic'
) 

I think draw_pichart method in tree.py does not get new fontname.
https://github.com/parrt/dtreeviz/blob/master/dtreeviz/trees.py#L1061

**Comment by mepland** [comment]
@parrt this should be resolved now.

**Comment by parrt** [comment]
Fixed by https://github.com/parrt/dtreeviz/pull/224 ? @mepland

**Comment by mepland** [comment]
@parrt should be!
