### ISSUE TITLE
List index out of range error fix

### ISSUE THREAD

**Issue by ssimmons9212** [parrt/dtreeviz#146]
getting this error when attempting to pass my dataset through dtreeviz

IndexError                                Traceback (most recent call last)
<ipython-input-60-540c80b2eb63> in <module>
----> 1 viz = dtreeviz(clf, Xtrain_set, ytrain_set,
      2                 target_name="target",
      3                 feature_names=pkg_data.feature_names,
      4                 class_names=list(pkg_data.target_names))
      5 

~\Anaconda3\lib\site-packages\dtreeviz\trees.py in dtreeviz(tree_model, x_data, y_data, feature_names, target_name, class_names, tree_index, precision, orientation, instance_orientation, show_root_edge_labels, show_node_labels, show_just_path, fancy, histtype, highlight_path, X, max_X_features_LR, max_X_features_TD, label_fontsize, ticks_fontsize, fontname, title, title_fontsize, colors, scale)
    762 
    763     n_classes = shadow_tree.nclasses()
--> 764     color_values = colors['classes'][n_classes]
    765 
    766     # Fix the mapping from target value to color for entire tree

IndexError: list index out of range

**Comment by parrt** [comment]
it can only handle 10 classes I think at the moment. how many do you have?
