### ISSUE TITLE
Update doc to indicate numeric targets required (Was: Value error with TfidfVectorizer and DecisionTreeClassifier)

### ISSUE THREAD

**Issue by reneverheij** [parrt/dtreeviz#150]
Hi,
I'm developing a classifier for documents using TfidfVectorizer and DecisionTreeClassifer (sklearn). I would like to use dtreeviz to visualize the resulting decision tree. I'm a bit stuck, and getting the folloing stacktrace:

```
  File "src/cogoro/train/oro.py", line 99, in oro_mlp_main
    viz = dtreeviz(clf, X.toarray(), y, target_name="aktesoort",
  File "/srv/data/verhr25/git/cog-dni-oro/venv38/lib64/python3.8/site-packages/dtreeviz/trees.py", line 792, in dtreeviz
    class_split_viz(node, X_data, y_data,
  File "/srv/data/verhr25/git/cog-dni-oro/venv38/lib64/python3.8/site-packages/dtreeviz/trees.py", line 986, in class_split_viz
    hist, bins, barcontainers = ax.hist(X_hist,
  File "/srv/data/verhr25/git/cog-dni-oro/venv38/lib64/python3.8/site-packages/matplotlib/__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/srv/data/verhr25/git/cog-dni-oro/venv38/lib64/python3.8/site-packages/matplotlib/axes/_axes.py", line 6571, in hist
    x = cbook._reshape_2D(x, 'x')
  File "/srv/data/verhr25/git/cog-dni-oro/venv38/lib64/python3.8/site-packages/matplotlib/cbook/__init__.py", line 1400, in _reshape_2D
    raise ValueError(f'{name} must have 2 or fewer dimensions')
```

My code looks roughly like this:
```
    vectorizer = factory.get_tfidf_vectorizer(train_df, max_features=25000)
    X = vectorizer.transform(train_df['text'].array)
    y = train_df["target"]
    unique_classes = train_df.target.unique().tolist()
    clf = train(X, y)
    viz = dtreeviz(clf, X.toarray(), y, target_name="target", 
                   feature_names=vectorizer.get_feature_names(), 
                   class_names=unique_classes)

```
The last line is where the ValueError occurs. I'm guessing it has something to do with the type or dimensions of X, which is the output of the TfidfVectorizer. Should I be able to do this, or is dtreeviz unable to handle this type?

Please advise,
Thanks

**Comment by tlapusan** [comment]
hi @reneverheij ,

I think you are right, it should has something with the dimensions of X.
The error happens when it tries to build the node visualisation, in method class_split_viz(), at these lines :
`
X_hist = [X_node_feature[y_train == cl] for cl in class_values]

hist, bins, barcontainers = ax.hist(X_hist,
                                            color=X_colors,
                                            align='mid',
                                            histtype=histtype,
                                            bins=bins,
                                            label=class_names)`

Could you make some debug on it ? 

Also, if you could make your notebook public, I would be happy to look over it. Without the actual data and the code, is kind of hard to understand where the problem comes from.

**Comment by reneverheij** [comment]
Hi Tudor,

You ask me to 'make some debug on it'. What kind of information are you looking for?

Thanks,
René

**Comment by tlapusan** [comment]
I assume that the error comes from the way the X_hist variable is build using your dataset.
By debugging, I meant to take a closer look how this variable is build, either using the debugger from your IDE or simple put some print() in the library source code.

**Comment by reneverheij** [comment]
I think I have found it. Is it possible, that dtreeviz assumes the y_data values to be of a numeric type, and that it can't handle string values?

**Comment by parrt** [comment]
Just about all models assume numeric values I would say, but some might automatically do labeling coding for non-numerics.  Anyway, yes, we assume everything is numeric.

**Comment by reneverheij** [comment]
I think that generally speaking, classifier models are happy to accept alphanumeric labels, at least SGDClassifier, MLPClassifier and DecisionTreeClassifier. I think you should consider supporting it, or at least mention this limitation in the documentation for your library.

**Comment by parrt** [comment]
Hm... interesting. I could swear I used to get errors all the time if I didn't transform my target variable.

**Comment by tlapusan** [comment]
Many of ML algorithms are supporting string labels, but behind they are labeling the data into numeric types. 

@parrt I've created this PR : https://github.com/parrt/dtreeviz/pull/152
Do you think we should do something more than just updating the docs ? I've searched for pandas and np.ndarray something related to type hints... but didn't find a concrete solution.

@reneverheij I've updated the docs, your point of view regarding the docs is valid. Thanks.

**Comment by parrt** [comment]
Well, we can leave for now.  First time this has come up.
