### ISSUE TITLE
dtreeviz IndexError for classifier with thousands of classes

### ISSUE THREAD

**Issue by premsaggar** [parrt/dtreeviz#151]
Hi, I love dtreeviz! I'm trying to use dtreeviz(clf) on a sklearn classfier that has thousands of classes! I'm getting:

IndexError: list out of range

Does dtreeviz support thousands of classes? What's the upper bound? Is there a workaround for many classes? 

Thank you so much,
Prem

**Comment by parrt** [comment]
Unfortunately, because we have to pick colors for the classes, it's currently limited to 10 :( sorry!
