### ISSUE TITLE
Will there be (is there) an .svg file export option? 

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [parrt/dtreeviz#158]
I can enjoy beautiful and informative dtreeviz visualisations for all major libraries when doing initial data inspection in Notebook, but this becomes infeasible if I conduct mass experiments which should be done in an ordinary python file in IDLE (visualization commands with .view() do not work as they do in Jupyter Notebook, leaving a constantly recreating blank window) and the generated pictures should be automatically saved somewhere, e. g. to .svg files. 

In Jupyter Notebook, I can manually save the rendered .svg-picture to a separate file, but this doesn't make the process automatic. 

Thanks in advance for a response!

**Comment by parrt** [comment]
Sorry...what is the question?

**Comment by gjirokastrelbasanit34** [comment]
Thanks for the answer, I deeply apologise for this totally blunt question, but I have always thought that the `.view()` and `.save()` methods implemented within `DTreeView` class only fit for Interactive Notebook environment, since every time when I call the `trees.dtreeviz()` in the standard python script, multiple windows continue to appear and clutter the screen view and I always thought that something has gone wrong and that these proliferating windows will just soon hang up my IDLE and PC if don't keyboard interrupt immediately, and I never had enough patience to wait until the end to meet the beautiful picture in the target directory. Moreover, when the script is called not in the environment, these temporary windows don't appear at all.
