### ISSUE TITLE
Question : How to plot  the complete emsemble ?

### ISSUE THREAD

**Issue by 3ntr0phy** [parrt/dtreeviz#162]
Hello,
I would be interested to understand if there is a better way to represent the whole ensemble instead of iterating through the whole set of tree indexes manually.
Just for being clear I am trying to visualize XGB GBDT and RF :)
Thanks!

**Comment by parrt** [comment]
Yeah, a great idea but really hard to figure out how we can implement this; I guess I will close it but thank you.
