### ISSUE TITLE
graphviz 0.18 pip library removed `run()` function from backend

### ISSUE THREAD

**Issue by parrt** [parrt/dtreeviz#163]
Currently dtreeviz only works with 0.17 graphviz.  Check new source here: https://github.com/xflr6/graphviz/blob/master/graphviz/backend/execute.py

**Comment by worthy7** [comment]
So what are we supposed to do to make this all work then?

I sort of expected the conda dtreeviz package to "just work"

**Comment by worthy7** [comment]
(for anyone else) I did this as a workaround and it worked:

`conda install -c conda-forge python-graphviz=0.17`

**Comment by parrt** [comment]
Fixed by 90031de435247632b75292e862e9697bb06479ca
