### ISSUE TITLE
`sklearn.utils.compute_class_weight` incorrectly called by dtreeviz

### ISSUE THREAD

**Issue by thomsentner** [parrt/dtreeviz#166]
When trying to plot my tree, I got the following error:

```
/opt/anaconda/envs/swb/lib/python3.7/site-packages/dtreeviz/models/sklearn_decision_trees.py in get_class_weights(self)
     28         if self.is_classifier():
     29             unique_target_values = np.unique(self.y_data)
---> 30             return compute_class_weight(self.tree_model.class_weight, unique_target_values, self.y_data)
     31 
     32     def get_thresholds(self):

TypeError: compute_class_weight() takes 1 positional argument but 3 were given
```

Looking at [sklearn's documentation](https://scikit-learn.org/stable/modules/generated/sklearn.utils.class_weight.compute_class_weight.html), dtreeviz should have called the function as such:
```python
compute_class_weight(self.tree_model.class_weight, classes=unique_target_values, y=self.y_data)
```

I've implemented a monkey patch for myself, which resolves the error.

**Comment by tlapusan** [comment]
Hi @thomsentner, I don't see a difference in proposed method call, it only uses named parameters, which is a default option in python.

Can you double check it please? Thanks

**Comment by thomsentner** [comment]
Sklearn includes a star in its function definition:

```python
sklearn.utils.class_weight.compute_class_weight(class_weight, *, classes, y)
```

As per [PEP 3102](https://www.python.org/dev/peps/pep-3102/), this means that any arguments right of the star are keyword-only arguments.

Some example code:

```python
def my_func(x, *, a):
    print(a)

# this works
my_func(1, a="a")

# this doesn't work
my_func(1, "a")
```

Output:

```
>>> my_func(1, a="a")
a
>>> my_func(1, "a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: my_func() takes 1 positional argument but 2 were given
```

**Comment by tlapusan** [comment]
Thanks @thomsentner, didn't know this feature. I'm in vacation right know. Will try to solve it soon
