### ISSUE TITLE
AttributeError: module 'lightgbm' has no attribute 'num_trees'

### ISSUE THREAD

**Issue by To-be-or-not** [parrt/dtreeviz#168]
Hi all,
     I could run the  example 'xxx_lightgbm_xxx.ipynb''' well, getting every plot. But when I tried it with my code, I found a problem like 'AttributeError: module 'lightgbm' has no attribute 'num_trees''. Sorry for that, It should not be a general problem, but I did not make it clear what is the issue. It seems I did get the Booster well.
```
Traceback (most recent call last):
  File "/Users/xin/OneDrive/program/ML/ML_analysis/GG_ML/LGBM/analysis.py", line 165, in <module>
    main()
  File "/Users/xin/OneDrive/program/ML/ML_analysis/GG_ML/LGBM/analysis.py", line 132, in main
    training.lgmTrain(pdData[0], MLParas, modelFolder, trainSize,pdData[1])
  File "/Users/xin/OneDrive/program/ML/ML_analysis/GG_ML/LGBM/training.py", line 68, in lgmTrain
    light_dtree = ShadowLightGBMTree(lgb, tree_index=1, x_data=X_train, y_data=Y_train, feature_names=features, target_name='variety', class_names=[0,1] )
  File "/usr/local/lib/python3.9/site-packages/dtreeviz/models/lightgbm_decision_tree.py", line 24, in __init__
    utils.check_tree_index(tree_index, booster.num_trees())
AttributeError: module 'lightgbm' has no attribute 'num_trees'
```
In File "/usr/local/lib/python3.9/site-packages/dtreeviz/models/lightgbm_decision_tree.py", line 24: 
```
from collections import defaultdict
from typing import List, Mapping

import numpy as np
import pandas as pd
import lightgbm as lgb
from lightgbm.basic  import Booster

from dtreeviz.models.shadow_decision_tree import ShadowDecTree, VisualisationNotYetSupportedError
from dtreeviz import utils


class ShadowLightGBMTree(ShadowDecTree):

    def __init__(self,
                 booster: Booster,
                 tree_index: int,
                 x_data: (pd.DataFrame, np.ndarray),
                 y_data: (pd.Series, np.ndarray),
                 feature_names: List[str] = None,
                 target_name: str = None,
                 class_names: (List[str], Mapping[int, str]) = None):

        **utils.check_tree_index(tree_index, booster.num_trees())**
        self.booster = booster
        self.tree_index = tree_index
        self.tree_nodes, self.children_left, self.children_right = self._get_nodes_info()
        self.thresholds = None  # lazy evaluation
        self.features = None  # lazy evaluation
        self.node_to_samples = None

```

Could you please take a look? Thank you very much!

Best,
Xin

**Comment by tlapusan** [comment]
Hi Xin,

Could you run these lines of code in both "xxx_lightgbm_xxx.ipynb" and your notebook ? Important to see if they will have the same outputs.

<img width="1088" alt="Screenshot 2021-12-07 at 09 20 39" src="https://user-images.githubusercontent.com/12815158/144984348-8453c99d-f90c-4e6f-8409-3409bb812713.png">

The error message "module 'lightgbm' has no attribute 'num_trees'" is a little strange, because you are calling num_trees() on booster object.

**Comment by To-be-or-not** [comment]
Hi Tudor,
     Thank you very much! Actually, What I was asking is a typing mistake. I input the model name wrongly. Now it is all fine.
     Thanks a lot for your nice and beautiful work!

Cheers,
Xin
