### ISSUE TITLE
Bars at data limits not plotted

### ISSUE THREAD

**Issue by david-macleod** [parrt/dtreeviz#17]
Hi

I have an issue where the bars at the limits of the data range are not being plotted, this is particularly problematic when the feature cardinality is 2. It only happens for particular input values but I have not yet been able to find the relationship between those which are successfully plotted and those which are not.

A reproducible example:

#### Correct result
```python
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from dtreeviz.trees import dtreeviz

x = np.random.choice([0,1], size=(100,2))
y = np.random.choice([0,1], size=100)

dtreeviz(
    tree_model=DecisionTreeClassifier(max_depth=1).fit(x, y),
    X_train=x,
    y_train=y,
    feature_names=['a','b'],
    target_name='y',
    class_names=[1,0]
)
```
<img width="207" alt="dtreeviz_correct" src="https://user-images.githubusercontent.com/17232877/46884319-8fc9bf00-ce4c-11e8-8749-69051ccf3728.PNG">

#### Incorrect result
```python
x = np.random.choice([-1,1], size=(100,2))
y = np.random.choice([0,1], size=100)

dtreeviz(
    tree_model=DecisionTreeClassifier(max_depth=1).fit(x, y),
    X_train=x,
    y_train=y,
    feature_names=['a','b'],
    target_name='y',
    class_names=[1,0]
)
```
<img width="209" alt="dtreeviz_incorrect" src="https://user-images.githubusercontent.com/17232877/46884329-96583680-ce4c-11e8-80a8-b49147bddce1.PNG">

Thank you for the library!

**Comment by parrt** [comment]
Thanks for the report!

**Comment by parrt** [comment]
@david-macleod actually, doesn't `np.random.choice([-1,1])` give same as `arange(-1,1)`, missing the 1?
