### ISSUE TITLE
Trying to visualize decision tree fitted with class weight, but got an error.

### ISSUE THREAD

**Issue by hugo-padovani** [parrt/dtreeviz#172]
I`m trying to visualize decision tree fitted with class weight, but got the following error.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/_x/jn2n6d5d2fx_r5dk4vgz3hs1bp6m_m/T/ipykernel_26821/2557380204.py in <module>
      9     class_names   = ["Detrator", "Neutro", "Promotor"],
     10     title         = "Decision Tree",
---> 11     scale         = 1.5
     12 )
     13 viz

~/.pyenv/versions/3.7.7/envs/nps_b2b/lib/python3.7/site-packages/dtreeviz/trees.py in dtreeviz(tree_model, x_data, y_data, feature_names, target_name, class_names, tree_index, precision, orientation, instance_orientation, show_root_edge_labels, show_node_labels, show_just_path, fancy, histtype, highlight_path, X, max_X_features_LR, max_X_features_TD, depth_range_to_display, label_fontsize, ticks_fontsize, fontname, title, title_fontsize, colors, scale)
    843                            filename=f"{tmp}/leaf{node.id}_{os.getpid()}.svg",
    844                            graph_colors=colors,
--> 845                            fontname=fontname)
    846             leaves.append(class_leaf_node(node))
    847         else:

~/.pyenv/versions/3.7.7/envs/nps_b2b/lib/python3.7/site-packages/dtreeviz/trees.py in class_leaf_viz(node, colors, filename, graph_colors, fontname)
   1098     # we visually need n=1 and n=9 to appear different but diff between 300 and 400 is no big deal
   1099     # size = np.sqrt(np.log(size))
-> 1100     counts = node.class_counts()
   1101     prediction = node.prediction_name()
   1102     draw_piechart(counts, size=size, colors=colors, filename=filename, label=f"n={nsamples}\n{prediction}",

~/.pyenv/versions/3.7.7/envs/nps_b2b/lib/python3.7/site-packages/dtreeviz/models/shadow_decision_tree.py in class_counts(self)
    609             else:
    610                 return np.round(
--> 611                     self.shadow_tree.get_node_nsamples_by_class(self.id) / self.shadow_tree.get_class_weights()).astype(
    612                     int)
    613         return None

~/.pyenv/versions/3.7.7/envs/nps_b2b/lib/python3.7/site-packages/dtreeviz/models/sklearn_decision_trees.py in get_class_weights(self)
     28         if self.is_classifier():
     29             unique_target_values = np.unique(self.y_data)
---> 30             return compute_class_weight(self.tree_model.class_weight, unique_target_values, self.y_data)
     31 
     32     def get_thresholds(self):

TypeError: compute_class_weight() takes 1 positional argument but 3 were given

Reproducing the error:
```
dt = DecisionTreeClassifier(class_weight='balanced') 
dt.fit(X_train, y_train)

fig = plt.figure(figsize=(20,20))

viz = dtreeviz(
    tree_model    = dt, 
    x_data        = X_train,
    y_data        = y_train,
    target_name   = 'NPS',
    feature_names = features, 
    class_names   = ["Detrator", "Neutro", "Promotor"],
    title         = "Decision Tree",
    scale         = 1.5
)
viz
```

**Comment by tlapusan** [comment]
Hi @hugo-padovani, can you check your scikit-learn version? mine is 0.24.2.

compute_class_weight() method is from scikit-learn and in my case is working fine with 3 arguments.

Thanks.

**Comment by tlapusan** [comment]
you could try it. At least let's see where the problem comes from :)

**Comment by hugo-padovani** [comment]
It worked. Thank you!
