### ISSUE TITLE
1.3.3 release timeline?

### ISSUE THREAD

**Issue by wlandecker-nextdoor** [parrt/dtreeviz#173]
Thank you for this helpful library! It looks like you've already started collecting commits for a 1.3.3 release, including [this fix](https://github.com/parrt/dtreeviz/pull/167), without which we can't use dtreeviz alongside the current sklearn. I'm curious if you have an anticipated release date for 1.3.3 in mind.

Thanks!

**Comment by tlapusan** [comment]
@parrt any plans for this ?

**Comment by tlapusan** [comment]
@wlandecker-nextdoor thanks ! I'm curious what you use the library for ?

**Comment by wlandecker-nextdoor** [comment]
I work in ML transparency / accountability. I often need to understand the "how?" captured by a model, to explain its strategy. This happens both during the development phase ("does this model explanation sound like a plausible solution to the real problem, or does it point to some kind of sampling bias that I need to correct?") and the production phase ("these decisions may have been surprising, but we can check their logic and see it's sensible.")

That said, I'm pinned to the most recent sklearn version so I haven't actually been able to use dtreeviz yet! But I would like to: I'm current working on a project that requires simple decision trees (lower predictive performance is acceptable, but high transparency is a requirement), and it would be helpful to visualize the distributions at each node of the tree.

**Comment by parrt** [comment]
Pushing 1.3.3 now!

**Comment by tlapusan** [comment]
> I work in ML transparency / accountability. I often need to understand the "how?" captured by a model, to explain its strategy. This happens both during the development phase ("does this model explanation sound like a plausible solution to the real problem, or does it point to some kind of sampling bias that I need to correct?") and the production phase ("these decisions may have been surprising, but we can check their logic and see it's sensible.")
> 
> That said, I'm pinned to the most recent sklearn version so I haven't actually been able to use dtreeviz yet! But I would like to: I'm current working on a project that requires simple decision trees (lower predictive performance is acceptable, but high transparency is a requirement), and it would be helpful to visualize the distributions at each node of the tree.

Sounds great. Glad that dtreeviz can help you!

**Comment by wlandecker-nextdoor** [comment]
Thank you so much!
