### ISSUE TITLE
Support for tensorflow - decision forest

### ISSUE THREAD

**Issue by tlapusan** [parrt/dtreeviz#181]
https://blog.tensorflow.org/2021/05/introducing-tensorflow-decision-forests.html

**Comment by tlapusan** [comment]
Implemented the basic necessary methods to be able to initialize a shadow tree. Still work to be done to add the first visualisations :)

<img width="1032" alt="Screenshot 2022-03-30 at 10 26 43" src="https://user-images.githubusercontent.com/12815158/160775635-9d05b1aa-bd05-4ce6-ad54-b1ed8d45c99f.png">

**Comment by parrt** [comment]
awesome!

**Comment by tlapusan** [comment]
First visualisation for RandomForest classification model !

<img width="611" alt="Screenshot 2022-05-02 at 09 56 27" src="https://user-images.githubusercontent.com/12815158/166196074-c9e02558-24c2-4f22-8108-45980848fe2d.png">

**Comment by parrt** [comment]
Woohoo!!!

**Comment by tlapusan** [comment]
even more visualisations !
<img width="739" alt="Screenshot 2022-05-07 at 20 06 08" src="https://user-images.githubusercontent.com/12815158/167264566-5c807948-73a8-4b1a-a326-4c6801ff4fb9.png">

**Comment by parrt** [comment]
woot!

**Comment by tlapusan** [comment]
And we have the main visualisation implemented also :)

<img width="728" alt="Screenshot 2022-08-03 at 10 51 07" src="https://user-images.githubusercontent.com/12815158/182554165-483db62e-2399-4952-b75b-704360be7bfb.png">

**Comment by parrt** [comment]
By the way I think in your examples you tend to pass the shadow tree around but nobody knows what that is so I think our example should avoid that unless you are specifically doing something for efficiency reasons.

**Comment by tlapusan** [comment]
By examples you mean this screenshots or visualisations from the notebook ? 

In the notebook I initialize the shadow tree like this : 
`tfdf_shadow = ShadowTFDFTree(model, tree_index=0, 
                             x_data=train[features], 
                             y_data=train[target], 
                             feature_names=features, 
                             target_name=target,
                             class_names=[0, 1])`
and send it to the visualisations instead of using the other method of sending a long list of parameters for each.

**Comment by parrt** [comment]
I just meant no one knows what a shadow tree is. Why expose that in normal circumstances to the user?

**Comment by tlapusan** [comment]
Indeed, if somebody is looking to the above screenshoot, they wouldn't know what a tfdf_shadow is.

But if the user is looking through the notebook visualisations, he/she will have access to the initialization step for tfdf_shadow.

**Comment by parrt** [comment]
True, but I just want to make sure we show the simplest possible interface for most people. Those were efficiency issues can dig deeper.
