### ISSUE TITLE
Cannot change the colors for classes in dtreeviz

### ISSUE THREAD

**Issue by utopianf** [parrt/dtreeviz#195]
I cannot reproduce the 9th cell in [colors.ipynb](https://github.com/parrt/dtreeviz/blob/master/notebooks/colors.ipynb). The color kept default and did not change.

The version of dtreeviz is 1.3.3, installed by conda in Windows 10.

**Comment by utopianf** [comment]
Sorry for bothering you again, but I solved this problem.
I installed from repository using `pip -e install .` then it works. The version is now 1.3.7

**Comment by utopianf** [comment]
@hannesrosenbusch MYCOLORS should not be a dict but a list which is like the code below:
https://github.com/parrt/dtreeviz/blob/e74641d8fa19a68df4e6a7c6bdd94c3d86a9c867/dtreeviz/colors.py#L18-L31

**Comment by hannesrosenbusch** [comment]
Thanks for the super quick reply. After updating to version 1.4.0 the following code works :) 

`mycolors = {"classes": [None, None, ["red", "blue"]]}
viz = dtreeviz.trees.dtreeviz(m, x_data=X.values, y_data=y, feature_names=X.columns, class_names=["No", "Yes"], colors=mycolors)
`
