### ISSUE TITLE
rtreeviz_univar() does not show X feature properly

### ISSUE THREAD

**Issue by parrt** [parrt/dtreeviz#198]
Looking in the colors notebook I see the following image with `[WGT]` as the X feature.
<img width="586" alt="Screen Shot 2022-10-29 at 11 29 12 AM" src="https://user-images.githubusercontent.com/178777/198847330-b8076bfb-9959-4cbc-9722-3e65f59218b6.png">

**Comment by mepland** [comment]
@parrt I fixed this here https://github.com/parrt/dtreeviz/pull/245. The `feature_names` list wasn't being indexed for the x-axis.

**Comment by parrt** [comment]
thanks!
