### ISSUE TITLE
`ctree_leaf_distributions()` should use the classnames not classes

### ISSUE THREAD

**Issue by parrt** [parrt/dtreeviz#202]
Line 1549 of trees.py func `ctree_leaf_distributions()` should use the classnames not classes:

```
ax.legend([bar_container0, bar_container1],
          [f'class {self.shadow_tree.classes()[0]}', f'class {self.shadow_tree.classes()[1]}'])
```
<img width="1004" alt="Screenshot 2022-12-03 at 1 08 41 PM" src="https://user-images.githubusercontent.com/178777/205462173-fb661725-69fd-4444-9a8f-532a4c34d37c.png">

**Comment by parrt** [comment]
Actually, it looks like that function is also limited to binary Target where as it should be any number of target. And I guess the code can simply call add_classifier_legend() instead of creating its own legend.

**Comment by mepland** [comment]
@parrt fixed in https://github.com/parrt/dtreeviz/pull/221
