### ISSUE TITLE
Prediction path explanation should show comparisons in order of node discovery

### ISSUE THREAD

**Issue by parrt** [parrt/dtreeviz#204]
Currently the output for the prediction path is given in the feature order in the data frame.

**Comment by mepland** [comment]
Do we want to only display the features used in the prediction? I think the user can print a dataframe row if they want all of the features, but including them is making the text box large, or adding the ellipsis.

![dtreeviz_pred_path](https://user-images.githubusercontent.com/4729931/210300006-df130d93-02d1-4440-aefd-4c7e396ae8be.png)

**Comment by tlapusan** [comment]
@mepland I think that @parrt is referring to this viz 
<img width="538" alt="Screenshot 2023-01-03 at 09 58 47" src="https://user-images.githubusercontent.com/12815158/210318635-9885d8d8-778a-4efe-9e7c-d278939a67eb.png">

**Comment by mepland** [comment]
@parrt @tlapusan done, see https://github.com/parrt/dtreeviz/pull/234

**Comment by parrt** [comment]
Regarding showing the entire instance of X, probably best to show at all but I can see a case where it's too big.

**Comment by parrt** [comment]
Closing per our discussion https://github.com/parrt/dtreeviz/pull/234#discussion_r1064108697
