### ISSUE TITLE
colors.py might be missing a previous merge?

### ISSUE THREAD

**Issue by parrt** [parrt/dtreeviz#222]
@tlapusan please see: https://github.com/parrt/dtreeviz/pull/185/files#diff-c79359e805463205f1a81b864ceee524b59f173b5dbd88111f2a9b256f9d65f2R32

**Comment by tlapusan** [comment]
what should be the bug ?

**Comment by parrt** [comment]
Sorry for the lack of clarity. It looks like that function is missing if you follow that link but I could be confused.
