### ISSUE TITLE
font name/size not respected

### ISSUE THREAD

**Issue by parrt** [parrt/dtreeviz#229]
in trees.py, the label font size arguments are ignoring but we should also be specifying the font.

```
def regr_leaf_node(node, label_fontsize: int = 12): ...
def class_leaf_node(node, label_fontsize: int = 12): ...
```
It eventually calls the node_label() func:

```
<font face="Helvetica" ...>
```

**Comment by parrt** [comment]
Well we are at it, we should look at this one. `ticks_fontsize` is ignored:

```
def _draw_barh_chart(counts, size, colors, filename, label=None, fontname="Arial", ticks_fontsize=9, graph_colors=None):
```

@mepland I think this one is a function you added so it might be fresh in your mind.

**Comment by mepland** [comment]
> Well we are at it, we should look at this one. `ticks_fontsize` is ignored:
> 
> ```
> def _draw_barh_chart(counts, size, colors, filename, label=None, fontname="Arial", ticks_fontsize=9, graph_colors=None):
> ```
> 
> @mepland I think this one is a function you added so it might be fresh in your mind.

`_draw_barh_chart()` doesn't actually draw any ticks currently, so we could probably just remove the `ticks_fontsize=9` parameter in this case.

Relatedly, I would like to replace most of this block:
```
    ax.spines['left'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    ax.spines['bottom'].set_visible(False)
    ax.tick_params(axis='x', which='both', top=False, bottom=False, left=False, right=False)
    ax.get_yaxis().set_visible(False)
```
with that axis formatting util function I mentioned as [point 2 here](https://github.com/parrt/dtreeviz/pull/200#issuecomment-1367704064).

**Comment by mepland** [comment]
> It eventually calls the node_label() func:
> 
> ```
> <font face="Helvetica" ...>
> ```

@parrt let's try to merge https://github.com/parrt/dtreeviz/pull/224 before messing with this code too much, to try and avoid merge issues.

**Comment by parrt** [comment]
> `_draw_barh_chart()` doesn't actually draw any ticks currently

I fixed that just now with https://github.com/parrt/dtreeviz/commit/5cf1b61f2519617435a7a971601c8987789440aa

**Comment by mepland** [comment]
@parrt has this issue been fully addressed in `dev` now?

**Comment by parrt** [comment]
Looking at the code it seems all right but I can't remember exactly what example I was running. Let's close
