### ISSUE TITLE
Standardize Capitalization

### ISSUE THREAD

**Issue by mepland** [parrt/dtreeviz#243]
We should standardize the capitalization in the plots, particularly on the axis labels where we have things like `feature`, `leaf ids`, `samples count` as well as `GINI`. Wouldn't `Feature`, `Leaf IDs`, `Samples Count`, and `Gini` be preferable?

**Comment by parrt** [comment]
Agreed. Capitalized per English rules is probably a good idea,  unless it's an acronym like MSE. is Gini an acronym? The other caveat is, it should be consistent with the decision tree library. If the library uses 'mse'to indicate the metric then we should use mse not MSE.

**Comment by mepland** [comment]
[Gini is a name](https://en.wikipedia.org/wiki/Decision_tree_learning#Gini_impurity), not an acronym. In this case the all uppercase style is coming from the `ShadowSKDTree` implementation:
```
    def criterion(self):
        return self.tree_model.criterion.upper()
```
We should remove the `.upper()` and take whatever `criterion` is provided by the model's library.

Sounds good, I'll make a PR to address this issue once https://github.com/parrt/dtreeviz/pull/236 and https://github.com/parrt/dtreeviz/pull/241 are merged!

**Comment by mepland** [comment]
Addressed in https://github.com/parrt/dtreeviz/pull/245!
