### ISSUE TITLE
Issue with import

### ISSUE THREAD

**Issue by cast42** [parrt/dtreeviz#25]
I do:
from dtreeviz.trees import *
I get:
NameError: name 'rtreeviz_univar' is not defined
when execuring 
```
t = rtreeviz_univar(ax,
                    X_train.WGT, y_train,
                    max_depth=2,
                    feature_name='Vehicle Weight',
                    target_name='MPG',
                    fontsize=14)
```

If i do:
```
from dtreeviz import trees
'dtreeviz' in dir(trees)
```
returns True
```
'rtreeviz_univar' in dir(trees)
```
returns  False
Strange

**Comment by parrt** [comment]
Hi. that must mean you have an old version. Can you do `pip install -U dtreeviz`?

**Comment by cast42** [comment]
The problem remains after:
'''
$ pip install -U dtreeviz
Requirement already up-to-date: dtreeviz in ./.conda/envs/omzet-gissen/lib/python3.7/site-packages (0.3.1)
'''
I think it has something to do with my conda packaging. I'll keep digging.

**Comment by parrt** [comment]
@cast42 probably a disconnect between conda environments or between conda and jupyter (if using that).
