### ISSUE TITLE
OSX:Display error in JupyterLab(Warning: No loadimage plugin for "svg:cairo")

### ISSUE THREAD

**Issue by xiaozhah** [parrt/dtreeviz#27]
Plaoform: Mac OS Mojave
Using Anaconda
Python -v: 3.7.1
Using `brew install graphviz --with-librsvg --with-pango` to install graphviz

if .dot files contain `digraph G { A -> B }`, `dot -Tsvg:cairo test.dot > test.svg` can produce plot successfully.

In jupyter Lab,it display this:
![image](https://user-images.githubusercontent.com/7589403/49681397-0812d080-fadc-11e8-89ca-d901f88e17d8.png)

In install the graphviz, it tells me that `icu4c is keg-only, which means it was not symlinked into /usr/local`, however it dot works and terminal tells me graphviz 2.40.1 is already installed and up-to-date

**Comment by parrt** [comment]
This must be some issue with the notebook invoking a different version of dot. Can you check the system path from notebooks? I am away from my computer for a day or two

**Comment by cod3licious** [comment]
I get a similar error and then it opens inkscape and displays this:
<img width="643" alt="screenshot 2018-12-15 at 23 51 32" src="https://user-images.githubusercontent.com/1093567/50048121-74856500-00c4-11e9-93aa-feda466220a5.png">
- any idea why it doesn't display the (incomplete) tree in jupyter notebook?

**Comment by parrt** [comment]
From notebook, try these:

```
import sys
sys.executable
```

Make sure that agrees with:

```
! which python
```

For me that is `/Users/parrt/anaconda3/bin/python`. 

The `PATH` should also be the same as from command line so it picks up correct `dot`.

```
import os
os.environ['PATH']
```

and

```
! echo $PATH
```

Those should be the same also.
