### ISSUE TITLE
viz.view() 

### ISSUE THREAD

**Issue by XiangYangAI** [parrt/dtreeviz#28]
I am running this in Jupyter Lab with nothing to show. I have installed all the dependency packages. Thanks for your help!
![2018-12-26_17-08-03](https://user-images.githubusercontent.com/42397178/50440502-81f6e680-0931-11e9-9039-95af140428ab.png)

**Comment by XiangYangAI** [comment]
The remote server is Ubuntu with anaconda virtual environment and I log in jupyter-lab on mac.

**Comment by XiangYangAI** [comment]
If I run all things on mac without using remote Ubuntu. Errors occur as follows:
```
Format: "svg:cairo" not recognized. Use one of: svg:svg:core
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-4-d2742afb20d1> in <module>
----> 1 viz.view()

~/anaconda3/lib/python3.6/site-packages/dtreeviz/trees.py in view(self)
     66         tmp = tempfile.gettempdir()
     67         svgfilename = f"{tmp}/DTreeViz_{getpid()}.svg"
---> 68         self.save(svgfilename)
     69         view(svgfilename)
     70 

~/anaconda3/lib/python3.6/site-packages/dtreeviz/trees.py in save(self, filename)
     89             cmd = ["dot", f"-T{format}:cairo", "-o", filename, dotfilename]
     90             # print(' '.join(cmd))
---> 91             stdout, stderr = run(cmd, capture_output=True, check=True, quiet=False)
     92 
     93         else:

~/anaconda3/lib/python3.6/site-packages/graphviz/backend.py in run(cmd, input, capture_output, check, quiet, **kwargs)
    157         stderr_write_bytes(err, flush=True)
    158     if check and proc.returncode:
--> 159         raise CalledProcessError(proc.returncode, cmd, output=out, stderr=err)
    160 
    161     return out, err

CalledProcessError: Command '['dot', '-Tsvg:cairo', '-o', '/var/folders/mn/3rsprdf53zqfhr_z6nswd5340000gn/T/DTreeViz_41460.svg', '/var/folders/mn/3rsprdf53zqfhr_z6nswd5340000gn/T/DTreeViz_41460']' returned non-zero exit status 1.
```

**Comment by parrt** [comment]
that is the brew install issue I think. did you do 

```
brew install graphviz --with-librsvg --with-pango
```

Try uninstall graphviz then do that.

**Comment by H4dr1en** [comment]
I had the same issue with Jupyter Lab on Linux. Easy fix: calling `viz` instead of `viz.view()` works fine, as shown in the notebooks inside the repo.

**Comment by parrt** [comment]
i pushed 0.4 last night. can you see if that works for you as well?

**Comment by H4dr1en** [comment]
I installed dtreeviz yesterday using the master branch (installing from pypi didn't work, I had an error). So I have 0.4 and still need to call `viz` at the end of a jupyter lab cell instead of `viz.view()`

**Comment by parrt** [comment]
actually, i guess in notebooks you never call viz.view(). should be just a ref to viz which is an object that notebooks know how to display.
