### ISSUE TITLE
Example leaf size not proportional to number of samples

### ISSUE THREAD

**Issue by cdtennant** [parrt/dtreeviz#29]
OS: Windows 7 Enterprise
Python: 3.6.5
Running on Jupyter Notebook

I am able to recreate the tree visualization for the iris data set as given in README.md

![iris](https://user-images.githubusercontent.com/44101401/50905936-fb8eda00-13f1-11e9-9074-fc142ae72b67.png)

However, when I run on my own data set I find the peculiarity that one of the leaves ("Fault B") does not seem to be proportional to the number of sample (35) as the others are

![mydata](https://user-images.githubusercontent.com/44101401/50906009-29741e80-13f2-11e9-8c96-425f19a553eb.png)

This is an unwieldy data set and I tried to reproduce the issue after applying PCA to reduce the dimensionality, but the resulting decision tree looks good (i.e. the leaves appear appropriately sized)

![afterpca](https://user-images.githubusercontent.com/44101401/50906204-97204a80-13f2-11e9-9865-4fa14f70e3a4.png)

Very curious!

**Comment by parrt** [comment]
Thanks!  No doubt my [prop_size()](https://github.com/parrt/dtreeviz/blob/master/dtreeviz/trees.py#L1128) function is the issue!

**Comment by cdtennant** [comment]
FYI, I noticed that this issue actually appears in dtreeviz/notebooks/examples.ipynb for the iris data set as well:
![dtreeviz](https://user-images.githubusercontent.com/44101401/51986622-a08b5880-246e-11e9-9c8e-b235319b8e8e.png)
