### ISSUE TITLE
WARNING:matplotlib.font_manager:findfont: Font family 'Arial' not found.

### ISSUE THREAD

**Issue by hima2b4** [parrt/dtreeviz#293]
When run in colab, the following error message appears

WARNING:matplotlib.font_manager:findfont: Font family 'Arial' not found.

Please let me know if you know of a solution.

**Comment by Lich496** [comment]
`viz_model.view(fontname="monospace")`
Setting available font to `fontname` can be a solution.

**Comment by mepland** [comment]
Please see https://github.com/parrt/dtreeviz/issues/270.
