### ISSUE TITLE
MacOS: Error: invalid option: --with-librsvg

### ISSUE THREAD

**Issue by EricCacciavillani** [parrt/dtreeviz#33]
First off thank you for creating the dependency it looks incredible to use.
But sadly I cant seem to install graphiz. Following the instructions for issue #23 I am confused with what I am supposed to do:
1.) I have xcode-select installed
2.) I ran "sudo xcodebuild -license" from the command-line (I dont understand why...just to confirm I got it I guess.)
3.) I run "brew uninstall graphviz"
4.) then finally run "brew install graphviz --with-librsvg --with-pango" in command-line

Then I get the following error
`Error: invalid option: --with-librsvg`
![image](https://user-images.githubusercontent.com/16104771/52238194-6ddfc680-2899-11e9-9b12-631ff7230002.png)

Thank you in advance for any help.

**Comment by EricCacciavillani** [comment]
`Homebrew 2.0.0
Homebrew/homebrew-core (git revision bf83; last commit 2019-02-04)`

Some more context. (I don't see the options for what you specified...)
![image](https://user-images.githubusercontent.com/16104771/52238513-29a0f600-289a-11e9-8a9d-1024c09a3989.png)

Also thanks for the help!

**Comment by parrt** [comment]
hmm... yeah,Those options for the libraries are on the package.   when I asked for information I get the following:

```
$ brew info graphviz
graphviz: stable 2.40.1 (bottled), HEAD
Graph visualization software from AT&T and Bell Labs
https://www.graphviz.org/
/usr/local/Cellar/graphviz/2.40.1 (504 files, 11.3MB) *
  Built from source on 2018-12-06 at 14:22:07 with: --with-librsvg --with-pango
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/graphviz.rb
==> Dependencies
Build: pkg-config ✔
Required: gd ✔, gts ✘, libpng ✘, libtool ✔
==> Options
```

wow.  I get the error myself now. wth?!  something has changed.  This page seems to show that the option is valid but it's not working anymore:

https://formulae.brew.sh/formula/graphviz

it doesn't like the pango one either. crap.

**Comment by parrt** [comment]
well, crap. It appears they have removed the options. see here https://github.com/Homebrew/homebrew-core/blob/master/Formula/graphviz.rb

I can't even install it myself at the moment!!! damn!

**Comment by EricCacciavillani** [comment]
Dude that sucks! I am really sorry to hear that...well in the meantime, I can just try running it on my ubuntu machine.

**Comment by parrt** [comment]
no biggie :)  So svg comes out of linux no problem?

**Comment by EricCacciavillani** [comment]
![image](https://user-images.githubusercontent.com/16104771/52245031-0718d800-28ae-11e9-9018-ba5d278c3390.png)
Dude this is actually amazing...like seriously...

**Comment by EricCacciavillani** [comment]
I can work with that. I admit I want to work with floats at times for my data,  but then again binning is a thing and provides less overall noise in the dataset. So this will work for a majority of my datasets and dts but not all;(like 95% of the time this will be awesome) which again is still fantastic 

Thanks so much for your time. I will be suggesting this to other data scientists I know. (Most of em have a Ubuntu machine so this will work well for them. Hopefully, you find a way to fix the mac problem but it does seem like its going to be a living nightmare...like just why....)

**Comment by parrt** [comment]
Ok, try this:

```bash
brew uninstall graphviz
brew upgrade pango librsvg

cd /tmp
wget https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz
tar xvfz graphviz.tar.gz
cd graphviz-2.40.1/

rm -rf /usr/local/lib/graphviz # in case old stuff is there
./configure --includedir=/usr/local/include/graphviz
make -j 8 # 8 threads
make install
```

**Comment by parrt** [comment]
make sure it's using /usr/local/bin/dot not, for example, /Users/parrt/anaconda3/bin/dot

**Comment by EricCacciavillani** [comment]
I will give this a try in a tiny bit sorry was finishing up a presentation. Really sorry....also I am an idiot I thought you wanted the matrix to be ints only...thank god that isnt the case...I really need to sleep more...

**Comment by EricCacciavillani** [comment]
Yeah no getting the following error.....
![image](https://user-images.githubusercontent.com/16104771/52255106-1bc19400-28df-11e9-9a51-95d95b8cca5f.png)

**Comment by parrt** [comment]
Damn! is the date on that `dot` when you installed it?  And no errors from make or make install?

**Comment by EricCacciavillani** [comment]
Didn't look like any errors happened. I dont understand what you mean by the "date of that dot".

**Comment by parrt** [comment]
meaning timestamp `ls -l /usr/local/bin/dot`. i found an old one that didn't get overwritten earlier.

**Comment by EricCacciavillani** [comment]
![image](https://user-images.githubusercontent.com/16104771/52284908-5fde8400-2933-11e9-899a-e87ec9a0cff4.png)
Oh....

**Comment by parrt** [comment]
dang it! if it builds, this really should work. grrr....does your configure help show this:

```
$ ./configure --help|grep svg
  --with-rsvg=yes         rsvg library
$ ./configure --help|grep cairo
  --with-pangocairo=yes   pangocairo library
```

**Comment by EricCacciavillani** [comment]
Nope errors
![image](https://user-images.githubusercontent.com/16104771/52285850-1bec7e80-2935-11e9-9ad5-32203e886018.png)

**Comment by parrt** [comment]
the `--` is confusing grep. can you gry just the svg and cairo bits with grep like I did? thanks!

**Comment by EricCacciavillani** [comment]
![image](https://user-images.githubusercontent.com/16104771/52286049-7be32500-2935-11e9-9f5d-cc5217e88212.png)
this?

**Comment by parrt** [comment]
yup. ok, soooo weird. ok, let me try on a few other macs and let you know. i've reopened :) thanks much for the help.

**Comment by EricCacciavillani** [comment]
No problem I will keep revisiting for any updates.

**Comment by EricCacciavillani** [comment]
![image](https://user-images.githubusercontent.com/16104771/52319718-3e17e800-2999-11e9-980d-9a79e529b6e1.png)

**Comment by parrt** [comment]
dang. I tried that sequence on a 3rd mac and it worked well. 

How about doing a `make uninstall` from that build dir then make sure `dot` command says not found. Then do `make install` again (no need to clean and remake). Try `dot -Tsvg:cairo` again.

**Comment by EricCacciavillani** [comment]
Ok will give that a try

**Comment by parrt** [comment]
ok, that is really weird. only random thought. maybe there is an alias in the shell. try `/usr/local/bin/dot -Tsvg:cairo`?

**Comment by EricCacciavillani** [comment]
![image](https://user-images.githubusercontent.com/16104771/52356730-c088c200-2a02-11e9-9f5b-e9ec14954ee0.png)

**Comment by parrt** [comment]
rats! Hmm....ok, i'll wait to hear reports from others. maybe I'll try on another random mac. thanks!

**Comment by EricCacciavillani** [comment]
No problem thanks again!

**Comment by EricCacciavillani** [comment]
Wow still no one else dam....guess it's just me lol

**Comment by EricCacciavillani** [comment]
Np I'll live! I still got my Ubuntu machine! :3

**Comment by parrt** [comment]
ok, cool. i'll close for now.

**Comment by bminahan73** [comment]
I have this same issue.

**Comment by bminahan73** [comment]
have tried all of the steps posted here so far.

**Comment by bminahan73** [comment]
<img width="498" alt="screen shot 2019-03-03 at 12 18 00 pm" src="https://user-images.githubusercontent.com/27121305/53699493-6afbc700-3dae-11e9-8de9-1df1c8e6091c.png">

**Comment by parrt** [comment]
Have you tried what's on the home page?

```
brew uninstall graphviz
brew reinstall pango librsvg  # even if already there, please reinstall

cd /tmp
wget https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz
tar xvfz graphviz.tar.gz
cd graphviz-2.40.1/

rm -rf /usr/local/lib/graphviz # in case old stuff is there
# make sure to run ./configure after reinstalling pango, librsvg
./configure --includedir=/usr/local/include/graphviz
make -j 8 # 8 threads
make install
```

**Comment by pingwhistle** [comment]
I had to pass the `--with-pangocairo=yes` switch to the configure script. Without it, graphviz would compile without cairo support
```
./configure --includedir=/usr/local/include/graphviz --with-pangocairo=yes
```

**Comment by parrt** [comment]
wow. really? Ok,  I am adding to the readme. Thank you

**Comment by bminahan73** [comment]
@pingwhistle 's suggestion worked for me as well :D

**Comment by lutaev** [comment]
Hi there. I got the same error and I also tried all steps posted here. Here is my last actions:
```
brew uninstall graphviz  # it gives me an error No such keg: /usr/local/Cellar/graphviz

brew reinstall pango librsvg
cd /tmp
wget https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz
tar xvfz graphviz.tar.gz
cd graphviz-2.40.1/
rm -rf /usr/local/lib/graphviz
./configure --includedir=/usr/local/include/graphviz --with-pangocairo=yes
make -j 8 # 8 threads
make install
```
Then I run
```
dot -Tsvg:cairo
```
And got
```
Format: "svg:cairo" not recognized. Use one of: svg:svg:core
```

My mac data:
iMac (21.5-inch, Late 2012)
MacOS Mojave

Thanks.

**Comment by parrt** [comment]
Thanks. we need to know WHICH `dot` is running though.  What does `which dot` say?

**Comment by lutaev** [comment]
Thanks for attention. `which dot` says:
```
/usr/local/bin/dot
```

**Comment by parrt** [comment]
Hmm...that's correct. does `ls -l /usr/local/bin/dot` show your installation date?  and also try `rm ~/anaconda3/bin/dot` just to be sure.

**Comment by lutaev** [comment]
Command `ls -l /usr/local/bin/dot` says:
```
-rwxr-xr-x  1 mac  admin  22920 21 мар 18:18 /usr/local/bin/dot
```
and then `rm ~/anaconda3/bin/dot`:
```
rm: /Users/mac/anaconda3/bin/dot: No such file or directory
```

**Comment by parrt** [comment]
Dang. I'm at a loss I'm afraid. :(

**Comment by likejazz** [comment]
Same problem here.

```
$  dot -Tsvg:cairo
Format: "svg:cairo" not recognized. Use one of: svg:svg:core
$ ls -al /usr/local/bin/dot
-rwxr-xr-x  1 kaonpark  admin  22976 Apr  3 21:46 /usr/local/bin/dot
```

**Comment by breadplop** [comment]
I am also facing such an issue.
Running this:
```./configure --includedir=/usr/local/include/graphviz --with-pangocairo=yes```
I noticed that:
```
graphviz-2.40.1 will be compiled with the following:
...
...
plugin libraries:
  dot_layout:    Yes (always enabled)
  neato_layout:  Yes (always enabled)
  core:          Yes (always enabled)
  devil:         No (missing library)
  gd:            Yes
  gdiplus:       No (disabled by default - Windows only)
  gdk:           
  gdk_pixbuf:    No (gdk_pixbuf library not available)
  ghostscript:   No (missing Xrender)
  glitz:         No (disabled by default - incomplete)
  gtk:           No (gtk library not available)
  lasi:          No (missing pangocairo support)
  ming:          No (disabled by default - incomplete)
  pangocairo:    No (pangocairo library not available)
  poppler:       No (poppler library not available)
  quartz:        No (disabled by default - Mac only)
  rsvg:          No (rsvg library not available)
  visio:         No (disabled by default - experimental)
  webp:          No (disabled by default - experimental)
  xlib:          Yes
```
In particular: `  pangocairo:    No (pangocairo library not available)`

How can I get the pangocairo library?

Can't seem to find much information on the web, this seems like the most relevant and active thread around. 

Hope we can resolve this issue soon!

**Comment by parrt** [comment]
Hi. We have a potential solution but I haven't checked it yet: https://github.com/parrt/dtreeviz/pull/36  Can you try it?

**Comment by gautamkarnik** [comment]
Hi all, 

Hope this helps in some way.

It appears that svg:cairo is no longer supported on 10.14. I hear is what I did at home. I also tested on Windows 10:

```
brew uninstall graphviz
brew reinstall pango librsvg  # even if already there, please reinstall	
brew reinstall pango librsvg --build-from-source # even if already there, please reinstall
brew reinstall cairo --build-from-source
brew install graphviz --build-from-source
```

Then updated trees.py to only use dot -Tsvg, as per the pull request.  This however, does not solve the original font calculation problems that cairo solved, so some minor tweaks to this branch are needed.

You can also see what I had to do on Windows 10:

```
If you are having issues with run command you can try copying the following files from: https://github.com/xflr6/graphviz/tree/master/graphviz.

Place them in the AppData\Local\Continuum\anaconda3\Lib\site-packages\graphviz\site-packages\graphviz folder.

Clean out the __pycache__ directory too.
```

**Comment by parrt** [comment]
@lutaev @likejazz @breadplop are you folks on 10.13 or 10.14 os x?

**Comment by angelo-moreira** [comment]
@parrt I have the exact same issue I am running 10.14 followed the last pull request but no luck

**Comment by parrt** [comment]
Rats! Maybe @gautamkarnik, who has 10.14, can figure this out.

**Comment by likejazz** [comment]
@parrt I used to OS X 10.14 and still failed to install graphviz. but I've tried #36 and it works now!

**Comment by parrt** [comment]
Just got this working on a student's laptop. All i did was the preamble:

```
conda uninstall python-graphviz
conda uninstall graphviz
pip install dtreeviz
```

and then the os x instructions. works great on 10.13.

**Comment by parrt** [comment]
Fixed by https://github.com/parrt/dtreeviz/commit/b655c627abf87e07144132ea0bfbba21350d42ce
