### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by AlexandraBomane** [parrt/dtreeviz#34]
I trained a Sklearn CART model (using default parameters provided by Scikit-learn) on the attached data ([data.txt](https://github.com/parrt/dtreeviz/files/2900796/data.txt), where the column "Target" contains the labels to predict, the rest of the columns containing the values associated with features).

For model fitting, I used : 
`from sklearn.tree import DecisionTreeClassifier`
`from sklearn.utils.class_weight import compute_sample_weight`
`clf = DecisionTreeClassifier(random_state = 374564)`
`clf.fit(data.drop(['Target'], axis = 1).values, data['Target'].values, sample_weight = compute_sample_weight("balanced", data['Target'].values))`

I launched dtreeviz with the following command : 
`viz = dtreeviz(clf, data.drop(['Target'], axis = 1).values,
data['Target'].values, target_name='pred',
feature_names=feature_names,
class_names=["Class1", "Class2"])`

Then I got the following error message : 
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/bomane/anaconda3/lib/python3.7/site-packages/dtreeviz/trees.py", line 373, in dtreeviz
    filename=f"{tmp}/leaf{node.id}_{getpid()}.svg")
File "/home/bomane/anaconda3/lib/python3.7/site-packages/dtreeviz/trees.py", line 543, in class_leaf_viz
draw_piechart(node.class_counts(), size=size, colors=colors, filename=filename, label=f"n={node.nsamples()}")
File "/home/bomane/anaconda3/lib/python3.7/site-packages/dtreeviz/trees.py", line 728, in draw_piechart
i = np.nonzero(counts)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

Can you please tell me what could be the problem here ?

**Comment by parrt** [comment]
that's weird. it appears there's a leaf with no observations.  how many labels are in your target?

**Comment by AlexandraBomane** [comment]
2 labels : it is binary classification

**Comment by parrt** [comment]
any chance I could get a small dataset that exhibits this behavior?

**Comment by AlexandraBomane** [comment]
In my first message, I provided the exact dataset (data.txt) that I'm using and which leads to the error. It contains only 57 rows and 17 columns

**Comment by parrt** [comment]
oh sorry. read on my phone earlier. thanks!

**Comment by parrt** [comment]
I'm getting different error. have you done `pip install -U dtreeviz` to make sure you have latest? I'm getting 

```
  File "/Users/parrt/github/dtreeviz/dtreeviz/shadow.py", line 243, in feature_name
    return self.shadow_tree.feature_names[ self.feature()]
IndexError: list index out of range
```

either way...somethings wrong ;)  i'm investigating

**Comment by parrt** [comment]
Please `pip install -U dtreeviz`. Should work now. thanks!

**Comment by parrt** [comment]
@AlexandraBomane can you confirm it works?

**Comment by AlexandraBomane** [comment]
Hi @parrt, it works perfectly !

Many thanks for fixing the problem so quickly.
