### ISSUE TITLE
for classification problems, is there any limitations for max_depth of the estimator, only 3 layers? thanks

### ISSUE THREAD

**Issue by zhjTHU** [parrt/dtreeviz#35]

**Comment by parrt** [comment]
no limit. but max 10 levels of target classes.

**Comment by zhjTHU** [comment]
thanks, but I have met a error:
**UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 11528: illegal multibyte sequence**
is there any advice to solve this problem? (in my tree model, max_depth=5)

**Comment by parrt** [comment]
that is likely an issue with string handling unicode characters
