### ISSUE TITLE
Unable to get dot installed properly on Mac Mojave (10.14.4)

### ISSUE THREAD

**Issue by sv650s** [parrt/dtreeviz#37]
Hi,

I'm following the instructions on your github page to get dtreeviz working for a school project but it doesn't seem to be updating dot properly. I've ran your instructions multiple times. Also, found this thread and tried everything in there as well:

https://github.com/parrt/dtreeviz/issues/33

I've followed all the instructions to install on github page:

 (including uninstalling python-graphviz and graphviz and brew uninstall packages and downloading their package and doing a make install)

https://github.com/parrt/dtreeviz

I'm on a MacBook Pro 13" 2018 Mojave (10.14.4)

Was wondering if you might be able to help?

```
brew upgrade pango librsvg
Error: pango 1.42.4_1 already installed
Error: librsvg 2.44.13 already installed

```
My system is still finding dot from /usr/local/bin/dot

It also doesn't know anything about a `../Cellar/graphviz/2.40.1/bin/dot` directory

I also saw bunch of warnings when I did the make but didn't find any errors:
 

 ```
✔ /tmp/graphviz-2.40.1
20:34 $ which dot
/usr/local/bin/dot
 ✔ /tmp/graphviz-2.40.1
20:34 $ dot -Tsvg:cairo
Format: "svg:cairo" not recognized. Use one of: svg:svg:core
 ✘-1 /tmp/graphviz-2.40.1
20:35 $ lw -l
-bash: lw: command not found
 ✘-127 /tmp/graphviz-2.40.1
20:35 $ ls -l ../Cellar/graphviz/2.40.1/bin/dot
ls: ../Cellar/graphviz/2.40.1/bin/dot: No such file or directory
 ✘-1 /tmp/graphviz-2.40.1
```
 
here is a history of my commands for the install:

 ```
589  brew uninstall graphviz
  590  brew reinstall pango librsvg --build-from-source # even if already there, please reinstall
  591  brew reinstall cairo --build-from-source
  592  brew install graphviz --build-from-source
  593  brew info graphviz
  594  #./configure --includedir=/usr/local/include/graphviz --with-pangocairo=yes --with-rsvg=yes
  595  history
  596  make uninstall
  597  ./configure --includedir=/usr/local/include/graphviz --with-pangocairo=yes --with-rsvg=yes
  598  rm -rf /usr/local/lib/graphviz
  599  ./configure --includedir=/usr/local/include/graphviz --with-pangocairo=yes --with-rsvg=yes | tee make.log 2>&1
  600  #make -j 8 | tee
  601  mv make.log configure.log
  602  make -j 8 | tee make.log 2>&1
  603  make install | tee install.log 2>&1
  604  history
```

**Comment by parrt** [comment]
Hmm... sorry to hear that. We are working on a new solution that does not require all those fancy libraries. See https://github.com/parrt/dtreeviz/pull/36

**Comment by parrt** [comment]
If you pull latest master, install is now super simple / easy!
