### ISSUE TITLE
compare to shap?

### ISSUE THREAD

**Issue by zkurtz** [parrt/dtreeviz#40]
I'm new to this project but have previously used SHAP (https://github.com/slundberg/shap), so any documentation comparing/contrasting this toolset with SHAP would be interesting.

My quick take is that dtreeviz is primarily about visualization, whereas SHAP is primarily about numerical estimates of feature importance (plus visualizing these estimates). Is there any overlap? To the extent that they don't overlap, a demo that shows how to use dtreeviz and SHAP in complementary ways to more-fully explain a model could be useful.

**Comment by parrt** [comment]
Hi. SHAP is indeed very interesting but technically is model agnostic and is not really related to decision tree visualization. As far as I can tell there's no overlap.

**Comment by zkurtz** [comment]
OK, if you're strictly looking at the visualization of the trees and disinterested in the corresponding effect sizes of the features used for splits, than the overlap may indeed be zero. SHAP does not appear to visualize trees per se. But it does have tree-specific explanations (shap.TreeExplainer) as demoed [here](https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Census%20income%20classification%20with%20LightGBM.ipynb). I wonder if there might be a way to overlay SHAP values on your tree visualizations that combines the best of both.

**Comment by parrt** [comment]
yep, even their "fast" tree specific one is too slow to be useful from my experience.  I'm interested in feature importance, just not in this repo :)  thanks...
