### ISSUE TITLE
PMML Support

### ISSUE THREAD

**Issue by dav-ell** [parrt/dtreeviz#41]
Does this library have support for loading trees saved in [PMML](https://en.wikipedia.org/wiki/Predictive_Model_Markup_Language) files? If not, would there be any interest in supporting it? 

Tools like IBM's [SPSS](https://www.ibm.com/us-en/marketplace/spss-decision-trees) can export their decision trees in PMML XML. To have this library support it would potentially mean that enterprise customers no longer need to purchase SPSS in order to view their tree. It would also allow for easier distribution of a tree once created.

**Comment by dav-ell** [comment]
Just a note that a library exists to convert PMML files to sklearn Tree Classifiers: [sklearn-pmml-model](https://github.com/iamDecode/sklearn-pmml-model).

**Comment by parrt** [comment]
Well, once you convert to sklearn, they you can just call these. I'm not sure we need a PMML thing internally.
