### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by qarabati** [parrt/dtreeviz#50]
Thansk for the code and tutorial. I found it very useful.
I am getting TypeError in my dataset. I set up this easy dataset and still getting the same error. 

TypeError: can't multiply sequence by non-int of type 'float'

It maybe caused by feature_names because in your example you always used datasets that already have feature_names set up. Can you help me with that?

import pandas as pd
from sklearn import preprocessing, tree
from dtreeviz.trees import dtreeviz

Things = {'Feature01': [3,4,5,0], 
          'Feature02': [4,5,6,0], 
          'Feature03': [1,2,3,8], 
          'Target01': ['5','5','6','6']}
df = pd.DataFrame(Things,
                  columns= ['Feature01', 'Feature02', 
                            'Feature03', 'Target01']) 
y_variable=df[['Target01']]
X_variable=df[['Feature01', 'Feature02','Feature03']]

regressor = DecisionTreeRegressor(max_depth=2)  
regressor.fit(X_variable, y_variable)

dtreeviz(regressor,
         X_variable,
         y_variable,
         target_name='Target01',
         feature_names=['Feature01', 'Feature02','Feature03']#df.columns[0:3]
         
         )

**Comment by Ashafix** [comment]
* `y_train` needs to be a Pandas Series, in your snippet it is a Pandas DataFrame, if you remove one pair brackets it should be a Series
* `y_train` should be a Series of numbers and `class_names` should contain the mapping of the numerical ids to the class names
* I added an additional check/conversion in this pull request: #51 
* Can you try it with the modified code and updated library?

**Comment by qarabati** [comment]
I converted the y-train to Panda series by adding:
y_variable=  df.ix[:,3]
And now the code is working. Thank you so much!
