### ISSUE TITLE
Fix examples to use dtreeviz

### ISSUE THREAD

**Issue by parrt** [parrt/dtreeviz#54]
In [new examples](https://github.com/parrt/dtreeviz/blob/master/notebooks/tree_structure_example.ipynb)  the trees are displayed using the default sklearn not dtreeviz ;)  This is for @tlapusan :)

**Comment by tlapusan** [comment]
> In [new examples](https://github.com/parrt/dtreeviz/blob/master/notebooks/tree_structure_example.ipynb) the trees are displayed using the default sklearn not dtreeviz ;) This is for @tlapusan :)

I'll fix it soon
