### ISSUE TITLE
white space in feature names don't work

### ISSUE THREAD

**Issue by Whamp** [parrt/dtreeviz#6]
See pictures for code and Viz result.

I think the issue may be that my feature names contain spaces. Is it possible this could be causing issues ?

I'm running this on MacOS X Mojave, Jupyter Lab, Anaconda 5.2

An example feature name is '12M Realized Volatility_Amean'
![delimiter error](https://user-images.githubusercontent.com/1115485/46235223-3c288300-c32e-11e8-9109-888f82b8d8a7.PNG)

![viz result](https://user-images.githubusercontent.com/1115485/46235229-40ed3700-c32e-11e8-9c7e-db7ea6de17e3.PNG)

**Comment by parrt** [comment]
Ah! Must be spaces in the name, yes!!!  Noted.

**Comment by parrt** [comment]
Hmm...can you send me a single row and a header row of data?  This is working for me in jupyter lab on mac:

```python
from sklearn.datasets import *
from dtreeviz.trees import *
from IPython.display import Image, display_svg

# data from https://archive.ics.uci.edu/ml/datasets/User+Knowledge+Modeling
clf = tree.DecisionTreeClassifier(max_depth=3)
know = pd.read_csv("testing/data/knowledge.csv")
target_names = ['very_low', 'Low', 'Middle', 'High']
know['UN S'] = know['UNS'].copy()
know['P E G'] = know['PEG'].copy()
know = know.drop(['UNS','PEG'], axis=1)

know['UN S'] = know['UN S'].map({n: i for i, n in enumerate(target_names)})

X_train, y_train = know.drop('UN S', axis=1), know['UN S']
clf = clf.fit(X_train, y_train)

viz = dtreeviz(clf, 
               X_train,
               y_train,
               target_name='UN S',
               feature_names=X_train.columns.values,
               class_names=target_names,
               fancy=True)
viz
```

**Comment by parrt** [comment]
Hi @Whamp can you try the above and/or send me a few rows of data that don't work? thanks!

**Comment by parrt** [comment]
Per https://twitter.com/PrinceShiva074/status/1048350134134697984 it's better to use simple node names.
