### ISSUE TITLE
viz for leaf samples distribution

### ISSUE THREAD

**Issue by tlapusan** [parrt/dtreeviz#60]
I would like to propose a new vizualisation type for leaf samples : by histrogram.
It is useful when you want to easily see the general distribution of leaf samples, instead of individual leaf samples. 
More useful when there is a big tree with a lot of leaves and the bar plot vizualisation is hard to interpret. 
For implementation, this will add another value ('hist') for display_type parameter from viz_leaf_samples function.
The new vizualisation will look like this :

<img width="1021" alt="hist" src="https://user-images.githubusercontent.com/12815158/67085878-5850c980-f1a8-11e9-8943-55720ede118e.png">

- when we want to include a subset of leaf samples (when we want to exclude the outlier leaves, like that leaf with ±350 samples from above viz)
<img width="1013" alt="hist_filter" src="https://user-images.githubusercontent.com/12815158/67085879-5850c980-f1a8-11e9-8c34-c6bec1db4ed4.png">

@parrt what do you think about it ?

**Comment by parrt** [comment]
Heh, looks pretty cool!  I think it is useful. Let's add
