### ISSUE TITLE
Make leaf split plot for regressors to show distribution of leaf sample y's

### ISSUE THREAD

**Issue by parrt** [parrt/dtreeviz#63]
I wonder if a split plot per leaf would look ok; seems like it'd be useful, @tlapusan.  Here is a sample split plot.  Maybe one y range / axis on left and then tight grouping of split plots?

<img width="89" alt="Screen Shot 2019-10-28 at 10 44 58 AM" src="https://user-images.githubusercontent.com/178777/67703086-183fd280-f970-11e9-8276-e2d287521297.png">

**Comment by tlapusan** [comment]
I'm not sure if i understood correctly. Would you like to include all the leaf split plots into a single new visualisation ?

Something similar with this ? :)
![Uploading leaf_regressor.jpg…]()

**Comment by parrt** [comment]
yep, that's it!!!  Seems like it'd be useful just as the stacked histo is for classification

**Comment by tlapusan** [comment]
Cool ! Do you have any web resources/experience of how to include subplots (leaf sample'y distribution) into another plot using matplotlib ?

**Comment by parrt** [comment]
hahaha. i spent forever learning how to do that in this project. we shouldn't have to though. We can create a single plot that just does scattering with some noise for each leaf area. Here is [sample code](https://github.com/parrt/dtreeviz/blob/master/dtreeviz/trees.py#L1139):

```
    mu = .5
    sigma = .08
    X = np.random.normal(mu, sigma, size=len(y))
    ax.set_xlim(0, 1)
    alpha = colors['scatter_marker_alpha'] # was .25

    ax.scatter(X, y, s=5, c=colors['scatter_marker'], alpha=alpha, lw=.3)
    ax.plot([0,len(node.samples())],[m,m],'--', color=colors['split_line'], linewidth=1)
```

So, basically, go to each leaf id and do a scatter that is x = id+noise and the y is just the y of samples at that leaf. make sense?

**Comment by tlapusan** [comment]
Nicee, I got the idea. I will start to implement it in the next days.

**Comment by tlapusan** [comment]
While thinking about this new visualisation, I have remember the boxplot from matplotlib. I guess it's what we need : https://matplotlib.org/3.1.1/gallery/statistics/boxplot_demo.html.
It can show a lot of build in stats, like median, mean, quartiles, outliers, etc
@parrt what do you think ? 

![boxplot](https://user-images.githubusercontent.com/12815158/67762505-4267c200-fa4e-11e9-99fe-de7bf6c7f98e.png)

**Comment by parrt** [comment]
Only problem is that box plots are ugly ;)   The alpha channel helps density and human eye is really good at picking up spread of data.

**Comment by tlapusan** [comment]
Indeed, box plot are a little ugly :)). I will take a look at the code that you mentioned

**Comment by tlapusan** [comment]
I have an intermediate visualisation.
Here is how it looks for a tree with depth=3:
<img width="1017" alt="depth3" src="https://user-images.githubusercontent.com/12815158/67946106-3a905500-fbe9-11e9-8a5b-ba1246a26027.png">
depth=5:
<img width="1001" alt="depth5" src="https://user-images.githubusercontent.com/12815158/67946122-44b25380-fbe9-11e9-8c8f-ba0f4300247b.png">
depth=10:
<img width="1014" alt="depth10" src="https://user-images.githubusercontent.com/12815158/67946131-4c71f800-fbe9-11e9-8b07-c37225831fb8.png">

As we can see, the visualisations becomes hard to read/interpret when we have a lot of leaves.
@parrt do you have any feedback, suggestions ?

**Comment by parrt** [comment]
looking interesting. for one we should tighten and fix the x direction so it's always the same. also dots should be bigger and then alpha channel can make darker areas show higher density. maybe graph is a bit too tall too. :)  Maybe we add a `show` arg like rtree_univar that turns off x labels?  Or maybe just show prediction to make smaller?

**Comment by tlapusan** [comment]
1. 'for one we should tighten and fix the x direction so it's always the same.'
Do you mean to hardcode a fix value for figsize argument ?
2. 'also dots should be bigger and then alpha channel can make darker areas show higher density'
agree, we can also make the markersize configurable
3. 'Maybe we add a show arg like rtree_univar that turns off x labels? '
agree
4. Or maybe just show prediction to make smaller?
Do you mean to show only the horizontal black lines ?

**Comment by tlapusan** [comment]
@parrt could be an option to show the leaves in multiple plots when the number of leaves is big ?

Something like this : 
<img width="349" alt="depth" src="https://user-images.githubusercontent.com/12815158/68026070-329ee680-fcb7-11e9-9010-32fc1d59ae53.png">

**Comment by parrt** [comment]
Looking good! Yes, i suppose we could split up but that's harder to implement. maybe args that say leaf ID range min/max?

1. 'for one we should tighten and fix the x direction so it's always the same.'
Do you mean to hardcode a fix value for figsize argument ?
*I just meant that any specific leaf split plot should be same width; don't smear it out to fit graph width.  Graph width is function of how many leaves I think.*
2. 'also dots should be bigger and then alpha channel can make darker areas show higher density'
agree, we can also make the markersize configurable
*yep*
3. 'Maybe we add a show arg like rtree_univar that turns off x labels? '
agree
*cool*
4. Or maybe just show prediction to make smaller?
Do you mean to show only the horizontal black lines ?
*That would work. I was earlier thinking that the x labels beneath graph would show just prediction value rather than num samples as well. just to make smaller.*

**Comment by tlapusan** [comment]
I created a PR. We can add modifications on it.
I added the option to create more plots, with a specified number of leaves/plot (plot_leaf_count)

For 1 :
- I added a configurable figsize for the plot. In case of multiple plots, the last plot will keep the same width for leaves as others plots.
2. Done
3. in the end, I added show_leaf_labels bool parameter (similar with dtreeviz method), it seems to me more straightforward than show parameter (in case I don't want to display the x labels, I would have to initialize show=[]). 
4. removed the samples from the string.

<img width="503" alt="Screenshot 2019-11-02 at 16 26 30" src="https://user-images.githubusercontent.com/12815158/68072363-9693de80-fd8d-11e9-9517-999f3086ed4a.png">

**Comment by parrt** [comment]
Cool. What about just `20.4` not `age=20.4` to make even smaller. Then make `age` the overall x label?

**Comment by parrt** [comment]
actually that might look weird like it's the x-value when in fact it's the leaf id. hmm...what if we put the predicted value at the *top* and then we don't actually need an x tick label?  We'd just need "leaf id" or something for the grpah xlabel and then "age" for ylabel.

**Comment by tlapusan** [comment]
I created the horizontal implementation for visualisation. I like how it looks, it's a better option than multiple plots. I also added a configurable 'grid' parameter, which shows the grid in visualisation (it helps to identify leaf's dots). 

I feel that we need to came up with better values for x, y labels (like you pointed up in previous comment). 

<img width="358" alt="Screenshot 2019-11-04 at 19 13 39" src="https://user-images.githubusercontent.com/12815158/68142924-08f4f200-ff39-11e9-99ea-3f495145d64a.png">
<img width="231" alt="Screenshot 2019-11-04 at 19 16 02" src="https://user-images.githubusercontent.com/12815158/68142927-08f4f200-ff39-11e9-9bb8-50ceca9daa04.png">
<img width="232" alt="Screenshot 2019-11-04 at 19 16 11" src="https://user-images.githubusercontent.com/12815158/68142928-08f4f200-ff39-11e9-96bd-8d5c234fee38.png">

**Comment by parrt** [comment]
Yeah, certainly repeating the target name is not optimal. I'd suggest something like:

<img width="358" alt="foo" src="https://user-images.githubusercontent.com/178777/68145072-cd7f0700-fee9-11e9-9dde-d67d5410de21.png">

Also let's try to keep things tightened up with perhaps less vertical space between leaves?

**Comment by tlapusan** [comment]
"Yeah, certainly repeating the target name is not optimal. I'd suggest something like:"
I will make a little research how to put the label in the right side of y axis.

"Also let's try to keep things tightened up with perhaps less vertical space between leaves?" 
For this I will need to adjust the 'mu' and 'sigma' values and maybe the leaf index...

**Comment by parrt** [comment]
For spacing, i think just shrink total height of graph maybe?

**Comment by parrt** [comment]
For the text, you can pick an x and then `ax.text(x, y, "37.3")` but might have to turn off clipping at boundaries so it appears.  Or, set xlim to 20% more and turn off tick marks/labels for that part then `ax.text()` there.  beat it into submission!! haha

**Comment by tlapusan** [comment]
> For spacing, i think just shrink total height of graph maybe?
It shrinks a little, but there is still a lot of space. Because the standard deviation between dots is sigma=0.08, with mean = 0.5 (mu value). leaf index are from 1 to 1... tomorrow, I will play with different values for them.

**Comment by tlapusan** [comment]
- reduced the space between leaves. Created a parameter for these also (leaf_space)
- about y axis, I put "leaf prediction" as a label and leaf predictions for y ticks. I looks well for me, it makes the graph loaded with few information. @parrt what do you think ? :)

<img width="266" alt="Screenshot 2019-11-05 at 12 03 10" src="https://user-images.githubusercontent.com/12815158/68198231-4fdbf980-ffc4-11e9-815f-4a7d8d7bf3a8.png">

**Comment by parrt** [comment]
Looking better! I think it's confusing to see prediction on y. that should be "leaf" I think as you had it. :)  also maybe double thick the prediction bars?  Perhaps your split plots have a too-high variance, maybe tighten up more like 

<img src="https://user-images.githubusercontent.com/178777/67703086-183fd280-f970-11e9-8276-e2d287521297.png" width="100">

The idea is that it's kind of a "shaky line of dots". Might have to reduce alpha channel a bit depending on number of dots.

**Comment by tlapusan** [comment]
hi @parrt. 
- I added the y label in the right side of the plot.
- narrow the leaf dots visualisations
- double the prediction bars

Here it is how they look now :)

<img width="245" alt="Screenshot 2019-11-06 at 14 02 16" src="https://user-images.githubusercontent.com/12815158/68297044-b46b8700-009e-11ea-8e13-ecc8f569acfe.png">
<img width="198" alt="Screenshot 2019-11-06 at 14 02 41" src="https://user-images.githubusercontent.com/12815158/68297045-b46b8700-009e-11ea-8230-73618f099081.png">

**Comment by parrt** [comment]
wow!  now that is a damn fine looking plot, sir!   I will merge!
