### ISSUE TITLE
improve documentation on coloring

### ISSUE THREAD

**Issue by DJCordhose** [parrt/dtreeviz#68]
What would I need to do to change the colors of the classes? Maybe provide a simple example (in a notebook).

**Comment by Ashafix** [comment]
Did you have a look at the end of the readme file and notebooks/colors.ipynb?

If it doesn't answer your question, it should be added to the documentation.

**Comment by DJCordhose** [comment]
I have and have even read source code and made some experiments, but did not get it to work. Also looked at a notebook that did some coloring, but simply did not understand it.

**Comment by parrt** [comment]
Sounds like we need some simpler examples.

**Comment by DJCordhose** [comment]
Or maybe the API is just too complex. I don't know, because I still don't understand 😀

**Comment by Ashafix** [comment]
Right now the documentation says about the class colors:

> `classes` needs to be a list of lists of colors with a minimum length of your number of colors. The index is the number of classes and the list with this index needs to have the same amount of colors.  

The usage would be
```
class_colors = [None, # 0 classes
                None, # 1 class
                ["#FEFEBB","#a1dab4"], # 2 classes
                ["#ff0000","#00ff00",'#0000ff'], # colors were changed here
                ["#FEFEBB","#D9E6F5",'#a1dab4','#fee090'], # 4
                ["#FEFEBB","#D9E6F5",'#a1dab4','#41b6c4','#fee090'], # 5
                ["#FEFEBB",'#c7e9b4','#41b6c4','#2c7fb8','#fee090','#f46d43'], # 6
                ["#FEFEBB",'#c7e9b4','#7fcdbb','#41b6c4','#225ea8','#fdae61','#f46d43'], # 7
                ["#FEFEBB",'#edf8b1','#c7e9b4','#7fcdbb','#1d91c0','#225ea8','#fdae61','#f46d43'], # 8                                       ["#FEFEBB",'#c7e9b4','#41b6c4','#74add1','#4575b4','#313695','#fee090','#fdae61','#f46d43'], # 9
                ["#FEFEBB",'#c7e9b4','#41b6c4','#74add1','#4575b4','#313695','#fee090','#fdae61','#f46d43','#d73027'] # 10
]


classifier = tree.DecisionTreeClassifier(max_depth=2)
iris = load_iris()
classifier.fit(iris.data, iris.target)

dtreeviz.trees.dtreeviz(classifier,
                        iris.data,
                        iris.target,
                        target_name='variety',
                        feature_names=iris.feature_names,
                        class_names=["setosa", "versicolor", "virginica"],
                        colors={'classes': class_colors}
)

```

Any ideas on how to improve the documentation are appreciated and I'd be happy to add it to the documentation.

**Comment by DJCordhose** [comment]
What about simplifying that example to something much more basic as a first step?

**Comment by DJCordhose** [comment]
Very good, I can now do what I want! Thank you so much!
