### ISSUE TITLE
Getting "TypeError: 'module' object is not callable" while calling dtreeviz method

### ISSUE THREAD

**Issue by shan-96** [parrt/dtreeviz#72]
while running the code:

```
viz = dtreeviz(clf,
                   X_train,
                   y_train,
                   target_name='target_name',
                   feature_names=feature_names,
                   orientation=orientation,
                   class_names=["setosa",
                                "versicolor",
                                "virginica"],  # 0,1,2 targets
                   fancy=fancy,
                   X=X,
                   label_fontsize=label_fontsize,
                   ticks_fontsize=ticks_fontsize,
                   fontname=fontname)
```
getting error  as below:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-23-95e7c1fb5cfe> in <module>()
      3 #regr = regr.fit(X_train, y_train)
      4 
----> 5 viz = viz_tree(clf,X_train,y_train)
      6 viz.save("GermanCredit.svg") # suffix determines the generated image format
      7 viz.view()             # pop up window to display image

<ipython-input-22-c33325585be5> in viz_tree(clf, X_train, y_train, orientation, fancy, pickX, label_fontsize, ticks_fontsize, fontname)
     29                    label_fontsize=label_fontsize,
     30                    ticks_fontsize=ticks_fontsize,
---> 31                    fontname=fontname)
     32 
     33     return viz

TypeError: 'module' object is not callable
```

**Comment by p42ul** [comment]
For anyone else getting this error, this is due to how the example code imports the module.

If you run `from dtreeviz import *`, you won't get the necessary function.

Use `from dtreeviz.trees import dtreeviz` instead.

**Comment by parrt** [comment]
Hi @p42ul I can't find `from dtreeviz import *`. Can you point me where to look? I'll fix it :)

**Comment by parrt** [comment]
no problem!

**Comment by RajdeepTarafder** [comment]
from dtreeviz.trees import * 

# Import necessary libraries
import dtreeviz     # Visualize the decision tree using dtreeviz
viz = dtreeviz.trees(model,
               X,
               y,
               target_name='class',
               feature_names=iris.feature_names,
               class_names=iris.target_names.tolist())
               
 NameError: name 'dtreeviz' is not defined

**Comment by Mirza-Ahmad** [comment]
from dtreeviz.trees import *
from dtreeviz.trees import dtreeviz
I have used both libraries but still error occured. Error: module object is not callable

**Comment by tlapusan** [comment]
@Mirza-Ahmad can you give us more details, dtreeviz version, code example? That error occurs when you try to use a Python module as if it were a function or callable object.

**Comment by Gejb01** [comment]
@tlapusan Hello, why is it that when I run the following code in PyCharm, no plot appears?
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
import dtreeviz

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Train the decision tree model
clf = DecisionTreeClassifier(max_depth=3)
clf.fit(X, y)

# Visualize the decision tree
viz = dtreeviz.model(clf, X, y,
                     feature_names=iris.feature_names,
                     class_names=iris.target_names)

# Display the visualization
viz.view()

**Comment by tlapusan** [comment]
Hi @Gejb01 , did you try it from notebook ? to be honest, I didn't try to see the library behavior from pycharm.

**Comment by Gejb01** [comment]
@tlapusan Thank you for your reply.Using your method, I obtained the visualization, but cannot save it, and received the following prompt: ''Traceback (most recent call last) Cell In[19], line 1 ----> 1 viz.save('model.svg') AttributeError: 'DTreeVizAPI' object has no attribute 'save'''. Why is this happening?Looking forward to your reply.

**Comment by tlapusan** [comment]
@Gejb01 would help to post also your code to better understand your issue :)

maybe this line of code will do your job:
`viz_model.view().save("./tree.svg")`

**Comment by Gejb01** [comment]
@tlapusan Thank you very much for your reply. I can now output the SVG image, but may I ask if it's possible to save it as a PDF file?

**Comment by tlapusan** [comment]
I guess you could use an image editor/converter for this.

**Comment by MitaliJain123** [comment]
@tlapusan again help me with the same 
1. Classification
viz = dtreeviz.model(clas, 
               X_train,
               y_train,
               feature_names=iris.feature_names, 
               class_names=["setosa", "versicolor", "virginica"]
               )
viz.view()
this is the code that I am using for some practice point of view but it is showing the below mentioned error.

NameError                                 Traceback (most recent call last)
Cell In[20], line 2
      1 #1. Classification
----> 2 viz = dtreeviz.model(clas, 
      3                X_train,
      4                y_train,
      5                feature_names=iris.feature_names, 
      6                class_names=["setosa", "versicolor", "virginica"]
      7                )
      8 viz.view()

NameError: name 'dtreeviz' is not defined
help me to resolve it

**Comment by tlapusan** [comment]
Hi @MitaliJain123, the error indicates that the dtreeviz library is not imported or installed in your environment.

**Comment by MitaliJain123** [comment]
but I checked it several times it is already installed
