### ISSUE TITLE
Plot in a for loop not shown in iPython notebook?

### ISSUE THREAD

**Issue by hackenjoe** [parrt/dtreeviz#73]
How can you plot a decision tree several times within a for loop such as 

    `for i in range(2):
    viz = dtreeviz(clf,
               iris['data'],
               iris['target'],
               target_name='',
               feature_names=np.array(iris['feature_names']),
               scale=2,
               class_names={0:'setosa',1:'versicolor',2:'virginica'})
            
    viz`

The Jupyter notebook doesnt show any output. Is there some kind of possibility to have an inplace plot several times or is this a limitation of your package?

**Comment by parrt** [comment]
Try `viz.view()` but that would pop up new window each time. you'll need to use subfigs or whatever to display all together in notebook.

**Comment by muneebaizaz** [comment]
diplay(viz) will show every plot

**Comment by parrt** [comment]
Hi. yeah, you'll Have to control which ones you want to show yourself. There's no way we can know a priori which ones you want. sorry.
