### ISSUE TITLE
How to visualize trees from cross-validation?

### ISSUE THREAD

**Issue by pplonski** [parrt/dtreeviz#85]
I'm doing 10-fold cross-validation and as a result, I have 10 trees. How to visualize them?

I assume that I need to do visualization for each tree. However, it can be not comfortable, because I will have 10 images and it will be hard to find similar patterns between trees. Is there a method to make a single visualization from many trees, that will show common patterns between trees?

What about the visualization of trees ensembles? Are you visualizing every single tree from the ensemble?

**Comment by parrt** [comment]
Hi. You will have to visualize each tree separately. I'm unaware of a way to compare the trees easily. One thing you could do is generate a text version of each tree and then use a difference tool to compare the  text representations.
