### ISSUE TITLE
How to get exact number of every class in split leaf?

### ISSUE THREAD

**Issue by RainFung** [parrt/dtreeviz#87]
Hello, i'm using the great tool for data analysing.  I want to know some exact number of every class in split leaf. Is there some method to get this number?
![image](https://user-images.githubusercontent.com/23121539/80077808-95937b00-8580-11ea-8b0d-8d496203b7a4.png)

How many green samples or yellow samples in circle?

**Comment by tlapusan** [comment]
hi @RainFung, glad to hear that your are using the library.

you can use many methods to find out this information.
<img width="876" alt="Screen Shot 2020-04-23 at 12 38 59 PM" src="https://user-images.githubusercontent.com/12815158/80084419-85b76f00-855f-11ea-8665-e6b31c515726.png">

Please take a look at `ctreeviz_leaf_samples` method. It can display leaf information both in text and plot. 
To get even more information from a specific leaf, you can use `describe_node_sample`. This method gives you stats aboud leaf samples, which can help you to discover patterns in your dataset.

I hope these methods will help you. Can you give us a shot feedback how/why are you using dtreeviz library ? thanks

**Comment by RainFung** [comment]
Thanks sir. It solves my problem. My goal is find the most important fact which classify the binary datasets.
