### ISSUE TITLE
why model need fit twice

### ISSUE THREAD

**Issue by qrsforever** [parrt/dtreeviz#89]
https://github.com/parrt/dtreeviz/blob/be7fccefbf46012b0403495adb91717b2cbc76b2/dtreeviz/shadow.py#L43

if not regr.fit(X_train, y_train) before dtreeviz, report error: 
AttributeError: 'DecisionTreeRegressor' object has no attribute 'tree_'
   
why not using hasattr to check: 

```py
    if not hasattr(tree_model, 'tree_'):
         tree_model.fit(X_train, y_train)
```

**Comment by parrt** [comment]
oh!You are correct! Do you want to send a pull request? thanks for catching this
