### ISSUE TITLE
Interactive visualizations?

### ISSUE THREAD

**Issue by thvasilo** [parrt/dtreeviz#92]
Hello, 

Thanks for the really cool project!

Looking at your visualization the first thing that jumped in my mind was how cool it would be if the visualizations had some form of interactivity through Bokeh or other libraries so users could hover over the figures and get extra information or interact with the models themselves.

Are there any plans to support something like that in the future?

**Comment by parrt** [comment]
Good idea. Sounds like plotly is free now. Only issue is the layout is buried in graphviz stuff. Might be hard to do anything interactive.

**Comment by oegedijk** [comment]
You  can check out my explainerdashboard library for interactively visualizing decision trees in random forests and xgboost models: [github.com/oegedijk/explainerdashboard](github.com/oegedijk/explainerdashboard)

**Comment by parrt** [comment]
I think I'm going to close this because we can't really rebuild this in an interactive toolkit.
