### ISSUE TITLE
Decision rules

### ISSUE THREAD

**Issue by MarkiMarki** [parrt/dtreeviz#93]
Hi there,

First of all, thanks for this wonderful package! it works pretty well and the visualizations are awesome

Concerning my problem-
The tree's figures (**viz.view()**) and the "Prediction path of a single observation" (from wine example) works fine, but when i try using the ShadowSKDTree (from dtreeviz_sklearn_visualisations.ipynb and so) im getting an error msg-
 "No module named 'dtreeviz.models'" 
(also cant initialize a shadow tree and related visualizations and functions as trees.describe_node_sample, trees.explain_prediction_path(sk_dtree, X, explanation_type="plain_english") and othres). 

Actually, what I'm trying to get is the **decision rules** (or boundaries) for a certain class for the relevant features (similarly to trees.explain_prediction_path), but what I'm trying to do is to extract them into a container (a list or preferably pandas' DataFrame- doesn't really matter..)

Would be very glad for some help! 
tips and leads are also welcome

Thanks

**Comment by tlapusan** [comment]
hi @MarkiMarki,

thanks for you feedback.
can you give us more details, a sample code or screenshot would be very helpful.

I assumed that you tried the wine example from examples.ipynb notebook. 
Here is my code containing ShadowSKDTree  implementation :
<img width="1338" alt="examples_notebook" src="https://user-images.githubusercontent.com/12815158/88685004-276dcf80-d0fe-11ea-8a8c-dbba80d591ab.png">

**Comment by MarkiMarki** [comment]
yes thank you-
I read and tried it
I'm adding a screenshot of one of my runs on my dataset (took off features' names from the nodes and the non-healthy group name)

![Untitled](https://user-images.githubusercontent.com/24315439/88689414-20958b80-d103-11ea-9531-d95c7a14b6f8.png)

As can be seen- the sum of features of the decision for the healthy group (below the pie's) are not correctly visible.

The technical problem is that it doesn't seem to be able to import the ShadowDecTree: 
when i run-
`from dtreeviz.models.shadow_decision_tree import ShadowDecTree`
i get-
`No module named 'dtreeviz.models'`

so.. i would like to get a corrected visualization of the decision path and more importantly- 
if you guys could also guide how the extract the decision paths for a specific class (as i mentioned above- to extract it as a list to some kind of container for later use..)

Thanks again!

**Comment by parrt** [comment]
Shouldn't that `trees.` be `dtreeviz...` ?

**Comment by parrt** [comment]
@tlapusan i wonder if the display issue is a font problem?

**Comment by MarkiMarki** [comment]
> Shouldn't that `trees.` be `dtreeviz...` ?

tried it.. doesn't seem to help

![Untitled1](https://user-images.githubusercontent.com/24315439/88765517-46607600-d17f-11ea-88d8-a06f31ce7e54.png)

Cant import nothing from **dtreeviz.models.shadow_decision_tree**

**Comment by MarkiMarki** [comment]
so.. how do i extract the decision paths to a container for later use? (not solely by visualizations)
Somewhere in the source code? 
@parrt @tlapusan have any thoughts?

(sorry for nudging guys but i'm definitely not an python expert)...

**Comment by tlapusan** [comment]
@MarkiMarki  you can you sklearn API to extract the decision paths.
you can take a look : 
1. https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier.decision_path
2. https://scikit-learn.org/stable/auto_examples/tree/plot_unveil_tree_structure.html

The last link contains a concrete example how to use decision_path.

**Comment by tlapusan** [comment]
@MarkiMarki 
![dtree_viz_issues](https://user-images.githubusercontent.com/12815158/88769909-b5d96400-d185-11ea-9f55-20d0703ff68a.png)

it seems that we already have many issues, some related, some unrelated to the library. What I would suggest for you, is to try to reproduce the examples from dtreeviz_sklearn_visualisations notebook.
By reproduce, I mean to write from scratch the visualization examples, using the titanic dataset. In this way, you will get used with the library and also we will see if your mentioned errors will repeat.

**Comment by parrt** [comment]
I'm going to close this and perhaps @MarkiMarki can submit new specialized issues. thanks everyone
