### ISSUE TITLE
Spark Decision Tree support

### ISSUE THREAD

**Issue by tlapusan** [parrt/dtreeviz#94]
Spark community lacks almost entirely model tree interpretation. Would be helpful to add support into dtreeviz.

I've already started to work on it and implemented two visualizations : 
<img width="921" alt="Screen Shot 2020-08-03 at 10 03 13 AM" src="https://user-images.githubusercontent.com/12815158/89154954-90c36780-d570-11ea-9eca-7451adde55ee.png">

**Comment by tlapusan** [comment]
hi @parrt ,

I implemented few more visualisations.
<img width="917" alt="Screenshot 2020-08-13 at 12 40 38" src="https://user-images.githubusercontent.com/12815158/90120024-009cd380-dd63-11ea-8a6b-9839ddeea7bf.png">
<img width="916" alt="Screenshot 2020-08-13 at 12 40 44" src="https://user-images.githubusercontent.com/12815158/90120036-0397c400-dd63-11ea-989b-7bccb0f74194.png">
<img width="918" alt="Screenshot 2020-08-13 at 12 41 02" src="https://user-images.githubusercontent.com/12815158/90120040-04305a80-dd63-11ea-8cc3-68a35ac5bbd9.png">
<img width="736" alt="Screenshot 2020-08-13 at 12 42 02" src="https://user-images.githubusercontent.com/12815158/90120043-04c8f100-dd63-11ea-8c0f-2e0e3587de5e.png">

An interesting think is that Spark has the concept of categorical split, where the threshold/split for a categorical feature is not a number, is a subset of feature categories values (you can see the highlights in one of my dtreeviz screenshot)
I needed to make some changes to make working the dtreeviz(). Do you have any feedback on it ?

**Comment by parrt** [comment]
Yes, the subset is a nice way to handle but expensive for large sets. Hmm...not sure how to visualize. we might need a new kind of decision node visualization. Hard part is displaying many labels. Something that other dude was complaining about

**Comment by tlapusan** [comment]
Indeed, if the set of categories is very large, we can have display issues.. but most of the time the set of categories is pretty small. 
Before building a new decision node, maybe we can wait for people feedback/complain about this potential issue, and meanwhile we can get more knowledge about how categories subsets are built.

**Comment by parrt** [comment]
sounds a good plan. Thanks again for all your help
